/**
 * bin/van.mjs against real scratch projects.
 * Named .unit.mjs so the browser test runner runs it as a child process.
 *
 * The CLI is exercised the way a consumer runs it — spawned, with --cwd — so
 * argv parsing, exit codes and stdout are all under test, not just the
 * exported helpers.
 */

import assert from "node:assert/strict"
import { spawnSync } from "node:child_process"
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, appendFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { fileURLToPath } from "node:url"
import { hashFile } from "../scripts/manifest.mjs"

const repoRoot = fileURLToPath(new URL("..", import.meta.url))
const VAN = join(repoRoot, "bin", "van.mjs")
const scratch = mkdtempSync(join(tmpdir(), "van-cli-"))

let passed = 0
let failed = 0

function test(name, fn) {
  const dir = join(scratch, name.replace(/[^\w]+/g, "-"))
  mkdirSync(dir, { recursive: true })
  try {
    fn(dir)
    passed++
  } catch (err) {
    failed++
    console.error(`FAIL ${name}\n  ${err.message}`)
  }
}

/** Run van in `dir`. Colour is off so assertions can match plain strings. */
function van(dir, ...args) {
  const r = spawnSync(process.execPath, [VAN, ...args, "--cwd", dir], {
    encoding: "utf8",
    env: { ...process.env, NO_COLOR: "1" },
  })
  return { code: r.status, out: r.stdout, err: r.stderr, all: r.stdout + r.stderr }
}

/** A project with a config written straight to disk, skipping init. */
function project(dir, config = {}) {
  writeFileSync(join(dir, "van.config.json"), JSON.stringify(config, null, 2) + "\n")
  for (const name of ["globals.css", "defaults.css", "forced-colors.css"]) {
    mkdirSync(join(dir, "styles"), { recursive: true })
    writeFileSync(join(dir, "styles", name), readFileSync(join(repoRoot, "styles", name)))
  }
  return dir
}

// ── init ────────────────────────────────────────────────────────────

test("init scaffolds a buildable tree", (dir) => {
  const r = van(dir, "init")
  assert.equal(r.code, 0, r.all)

  const config = JSON.parse(readFileSync(join(dir, "van.config.json"), "utf8"))
  assert.equal(config.paths.ui, "components/ui")
  assert.ok(config.theme.brand, "no starter brand colour")

  for (const name of ["globals.css", "defaults.css", "forced-colors.css", "van.css"]) {
    assert.ok(existsSync(join(dir, "styles", name)), `styles/${name} not written`)
  }

  // The first build must already reflect the scaffolded config.
  const css = readFileSync(join(dir, "styles", "van.css"), "utf8")
  assert.match(css, /^\/\* Generated by van/)
  assert.match(css, /--primary: light-dark\(/)

  // And a rebuild is a no-op, not an error.
  assert.equal(van(dir, "build").code, 0)
})

test("init refuses to clobber an existing config", (dir) => {
  van(dir, "init")
  writeFileSync(join(dir, "van.config.json"), '{ "theme": { "radius": "1rem" } }\n')
  const r = van(dir, "init")
  assert.equal(r.code, 1)
  assert.match(r.all, /already exists/)
  assert.match(readFileSync(join(dir, "van.config.json"), "utf8"), /1rem/, "config was overwritten")
})

test("init honours components.json aliases through tsconfig paths", (dir) => {
  writeFileSync(join(dir, "tsconfig.json"), '{"compilerOptions":{"paths":{"@/*":["./src/*"]}}}\n')
  writeFileSync(
    join(dir, "components.json"),
    '{"aliases":{"ui":"@/components/ui","utils":"@/lib/utils"},"tailwind":{"css":"src/app/globals.css"}}\n',
  )
  assert.equal(van(dir, "init").code, 0)

  const config = JSON.parse(readFileSync(join(dir, "van.config.json"), "utf8"))
  assert.equal(config.paths.ui, "src/components/ui")
  assert.equal(config.paths.lib, "src/lib")
  assert.equal(config.paths.styles, "src/app")
  assert.ok(existsSync(join(dir, "src/app/globals.css")), "stylesheets ignored the detected layout")
})

// ── add ─────────────────────────────────────────────────────────────

test("add dialog pulls its lib deps", (dir) => {
  project(dir)
  const r = van(dir, "add", "dialog")
  assert.equal(r.code, 0, r.all)
  assert.ok(existsSync(join(dir, "ui/dialog/dialog.jsx")))
  assert.ok(existsSync(join(dir, "ui/dialog/dialog.css")))
  assert.ok(existsSync(join(dir, "ui/dialog/.van.json")), "no provenance sidecar")
  assert.ok(existsSync(join(dir, "lib/cn.js")), "lib/ primitive not copied")
  assert.ok(existsSync(join(dir, "lib/use-controllable-state.js")))
})

test("add alert-dialog pulls dialog transitively and its CSS import resolves", (dir) => {
  project(dir)
  assert.equal(van(dir, "add", "alert-dialog").code, 0)

  const css = readFileSync(join(dir, "ui/alert-dialog/alert-dialog.css"), "utf8")
  const imports = [...css.matchAll(/@import\s+["']\.\.\/([^/"']+)\/([^"']+)["']/g)]
  assert.ok(imports.length, "alert-dialog.css no longer @imports a sibling — update this test")
  for (const [, slug, file] of imports) {
    assert.ok(existsSync(join(dir, "ui", slug, file)), `@import ../${slug}/${file} does not resolve`)
  }
})

test("add closes the lib graph transitively", (dir) => {
  project(dir)
  // popover -> lib/use-anchor-position.js -> lib/anchor-position.js
  assert.equal(van(dir, "add", "popover").code, 0)
  assert.ok(existsSync(join(dir, "lib/use-anchor-position.js")))
  assert.ok(existsSync(join(dir, "lib/anchor-position.js")), "second-order lib dep missing")
})

test("re-add refuses an edited file, and --overwrite replaces it", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const target = join(dir, "ui/badge/badge.css")
  appendFileSync(target, "/* my edit */\n")

  const refused = van(dir, "add", "badge")
  assert.equal(refused.code, 1, refused.all)
  assert.match(refused.all, /skipped badge \(badge\.css\)/)
  assert.match(readFileSync(target, "utf8"), /my edit/, "edit was destroyed without --overwrite")

  const forced = van(dir, "add", "badge", "--overwrite")
  assert.equal(forced.code, 0, forced.all)
  assert.doesNotMatch(readFileSync(target, "utf8"), /my edit/, "--overwrite did not replace the file")

  // --force is kept as an alias of --overwrite.
  assert.equal(van(dir, "add", "badge", "--force").code, 0)
})

test("re-add overwrites a file the consumer never touched", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const target = join(dir, "ui/badge/badge.css")

  // Simulate upstream having moved on: the local file still matches what was
  // recorded at install time, but no longer matches the kit.
  appendFileSync(target, "/* pretend this came from the kit */\n")
  const sidecarPath = join(dir, "ui/badge/.van.json")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = hashFile(target)
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const r = van(dir, "add", "badge")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /badge\.css updated/)
  assert.equal(
    readFileSync(target, "utf8"),
    readFileSync(join(repoRoot, "ui/badge/badge.css"), "utf8"),
    "unmodified file was not brought up to date",
  )
})

test("add rejects a slug that is not in the registry", (dir) => {
  project(dir)
  for (const slug of ["../evil", "../../etc/passwd", "/absolute", "nope"]) {
    const r = van(dir, "add", slug)
    assert.equal(r.code, 1, `accepted ${slug}`)
    assert.match(r.all, /unknown component/)
  }
  assert.ok(!existsSync(join(dir, "..", "evil")), "wrote outside the project root")
})

test("add --dry-run writes nothing", (dir) => {
  project(dir)
  const r = van(dir, "add", "badge", "--dry-run")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /nothing written/)
  assert.ok(!existsSync(join(dir, "ui/badge")), "--dry-run wrote files")
})

// ── diff ────────────────────────────────────────────────────────────

test("diff reports an edit and exits non-zero", (dir) => {
  project(dir)
  van(dir, "add", "badge")

  const clean = van(dir, "diff")
  assert.equal(clean.code, 0, clean.all)
  assert.match(clean.out, /match(es)? kit/)

  appendFileSync(join(dir, "ui/badge/badge.css"), "/* my edit */\n")
  const dirty = van(dir, "diff")
  assert.equal(dirty.code, 1)
  assert.match(dirty.out, /badge\.css — edited locally/)
})

test("diff calls it upstream movement when the local file matches the record", (dir) => {
  project(dir)
  van(dir, "add", "badge")

  // Same simulation as the add test: local still matches what was installed,
  // so the difference against the kit is upstream's, not the consumer's.
  const target = join(dir, "ui/badge/badge.css")
  appendFileSync(target, "/* pretend this came from the kit */\n")
  const sidecarPath = join(dir, "ui/badge/.van.json")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = hashFile(target)
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const r = van(dir, "diff", "badge")
  assert.equal(r.code, 1, "a difference must still exit non-zero")
  assert.match(r.out, /badge\.css — upstream changed/)
  assert.doesNotMatch(r.out, /edited locally/)
})

test("diff flags a file that is edited locally and changed upstream", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  appendFileSync(join(dir, "ui/badge/badge.css"), "/* my edit */\n")
  const sidecarPath = join(dir, "ui/badge/.van.json")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = "sha256-something-older"
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const r = van(dir, "diff", "badge")
  assert.equal(r.code, 1)
  assert.match(r.out, /badge\.css — edited locally, and upstream changed/)
})

test("diff reports a component with no sidecar as untracked", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  rmSync(join(dir, "ui/badge/.van.json"))
  appendFileSync(join(dir, "ui/badge/badge.css"), "/* my edit */\n")

  const r = van(dir, "diff", "badge")
  assert.equal(r.code, 1)
  assert.match(r.out, /no \.van\.json/)
  assert.match(r.out, /badge\.css — not recorded/)
})

// ── list / build / usage ────────────────────────────────────────────

test("list marks installed components", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const r = van(dir, "list")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /✓ badge/)
  assert.match(r.out, /^ {2}accordion/m, "uninstalled components should not be marked")
  assert.match(r.out, /1 installed/)
})

test("build without a config fails with a pointer to init", (dir) => {
  const r = van(dir, "build")
  assert.equal(r.code, 1)
  assert.match(r.all, /van init/)
})

test("build reports config errors instead of writing", (dir) => {
  project(dir, { theme: { brand: "not-a-colour" } })
  const r = van(dir, "build")
  assert.equal(r.code, 1)
  assert.match(r.all, /oklch/)
  assert.ok(!existsSync(join(dir, "styles/van.css")), "invalid config still produced CSS")
})

test("unknown flags and commands are errors", (dir) => {
  assert.equal(van(dir, "add", "--overwirte").code, 1)
  assert.match(van(dir, "add", "--overwirte").all, /unknown flag/)
  assert.equal(van(dir, "frobnicate").code, 1)
  assert.match(van(dir, "frobnicate").all, /unknown command/)
})

test("--silent suppresses output but not errors", (dir) => {
  project(dir)
  const ok = van(dir, "add", "badge", "--silent")
  assert.equal(ok.code, 0)
  assert.equal(ok.out.trim(), "", `--silent still printed: ${ok.out}`)

  appendFileSync(join(dir, "ui/badge/badge.css"), "/* edit */\n")
  const bad = van(dir, "add", "badge", "--silent")
  assert.equal(bad.code, 1)
  assert.match(bad.err, /skipped badge/)
})

// ── framework awareness ─────────────────────────────────────────────

test("next-app projects get a use client directive", (dir) => {
  mkdirSync(join(dir, "app"), { recursive: true })
  writeFileSync(join(dir, "package.json"), '{"dependencies":{"next":"15.0.0"}}\n')

  const init = van(dir, "init")
  assert.equal(init.code, 0, init.all)
  const config = JSON.parse(readFileSync(join(dir, "van.config.json"), "utf8"))
  assert.equal(config.framework, "next-app")
  assert.equal(config.rsc, true)
  assert.equal(config.paths.styles, "app", "App Router stylesheets belong in app/")

  assert.equal(van(dir, "add", "dialog").code, 0)
  const jsx = readFileSync(join(dir, "components/ui/dialog/dialog.jsx"), "utf8")
  assert.match(jsx, /^"use client"\n\n/, "hooks-using component has no directive")
  assert.doesNotMatch(
    readFileSync(join(dir, "components/ui/dialog/dialog.css"), "utf8"),
    /use client/,
    "directive injected into CSS",
  )

  // The sidecar records the injected bytes, so nothing reads as edited.
  const diff = van(dir, "diff")
  assert.equal(diff.code, 0, diff.all)
  const readd = van(dir, "add", "dialog")
  assert.match(readd.out, /0 files written/, "re-add rewrote an unchanged component")
})

test("non-rsc projects get no directive", (dir) => {
  writeFileSync(join(dir, "package.json"), '{"devDependencies":{"vite":"6.0.0"}}\n')
  mkdirSync(join(dir, "src"), { recursive: true })
  assert.equal(van(dir, "init").code, 0)

  const config = JSON.parse(readFileSync(join(dir, "van.config.json"), "utf8"))
  assert.equal(config.framework, "vite")
  assert.equal(config.rsc, false)
  assert.equal(config.paths.styles, "src/styles")

  assert.equal(van(dir, "add", "dialog").code, 0)
  assert.doesNotMatch(readFileSync(join(dir, "components/ui/dialog/dialog.jsx"), "utf8"), /use client/)
})

test("a stateless component gets no directive even under rsc", (dir) => {
  writeFileSync(join(dir, "package.json"), '{"dependencies":{"next":"15.0.0"}}\n')
  mkdirSync(join(dir, "app"), { recursive: true })
  van(dir, "init")
  assert.equal(van(dir, "add", "separator").code, 0)
  assert.doesNotMatch(
    readFileSync(join(dir, "components/ui/separator/separator.jsx"), "utf8"),
    /use client/,
    "directive added to a component with no hooks",
  )
})

// ── update ─────────────────────────────────────────────────────────

test("update reports up-to-date when nothing changed", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const r = van(dir, "update")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /up to date/)
})

test("update overwrites upstream-changed files and bumps the manifest", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const target = join(dir, "ui/badge/badge.css")

  // Simulate: local file matches what was installed (consumer didn't edit),
  // but upstream has moved on.
  appendFileSync(target, "/* pretend this came from the kit */\n")
  const sidecarPath = join(dir, "ui/badge/.van.json")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = hashFile(target)
  sidecar.kitVersion = "0.0.1"
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const r = van(dir, "update")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /badge\.css.*updated/)

  assert.equal(
    readFileSync(target, "utf8"),
    readFileSync(join(repoRoot, "ui/badge/badge.css"), "utf8"),
    "file was not brought up to date",
  )
  const after = JSON.parse(readFileSync(sidecarPath, "utf8"))
  assert.notEqual(after.kitVersion, "0.0.1", "manifest kitVersion not bumped")
})

test("update skips files the consumer edited when upstream is unchanged", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const target = join(dir, "ui/badge/badge.css")
  appendFileSync(target, "/* my edit */\n")

  const r = van(dir, "update")
  assert.equal(r.code, 0, r.all)
  assert.match(readFileSync(target, "utf8"), /my edit/, "consumer edit was clobbered")
})

test("update --dry-run writes nothing", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const target = join(dir, "ui/badge/badge.css")
  const sidecarPath = join(dir, "ui/badge/.van.json")

  // Make it look upstream-changed.
  appendFileSync(target, "/* old kit */\n")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = hashFile(target)
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const before = readFileSync(target, "utf8")
  const r = van(dir, "update", "--dry-run")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /nothing written/)
  assert.equal(readFileSync(target, "utf8"), before, "--dry-run wrote files")
})

test("update with no args updates all installed components", (dir) => {
  project(dir)
  van(dir, "add", "badge", "separator")

  // Make both look upstream-changed.
  for (const slug of ["badge", "separator"]) {
    const css = join(dir, `ui/${slug}/${slug}.css`)
    appendFileSync(css, "/* old */\n")
    const sp = join(dir, `ui/${slug}/.van.json`)
    const s = JSON.parse(readFileSync(sp, "utf8"))
    s.files[`${slug}.css`] = hashFile(css)
    writeFileSync(sp, JSON.stringify(s, null, 2) + "\n")
  }

  const r = van(dir, "update")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /badge\.css.*updated/)
  assert.match(r.out, /separator\.css.*updated/)
})

test("update --overwrite replaces diverged files", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const target = join(dir, "ui/badge/badge.css")
  appendFileSync(target, "/* my edit */\n")

  // Fake a different recorded hash so it looks diverged (local ≠ kit ≠ recorded).
  const sidecarPath = join(dir, "ui/badge/.van.json")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = "sha256-something-old"
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const r = van(dir, "update", "--overwrite")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /badge\.css.*overwritten/)
  assert.doesNotMatch(readFileSync(target, "utf8"), /my edit/, "edit survived --overwrite")
})

test("update reports diverged files when no git base is available", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  appendFileSync(join(dir, "ui/badge/badge.css"), "/* my edit */\n")

  const sidecarPath = join(dir, "ui/badge/.van.json")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = "sha256-something-old"
  sidecar.kitVersion = "0.0.0-nonexistent"
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const r = van(dir, "update")
  assert.equal(r.code, 1, "should exit non-zero on unresolvable conflicts")
  assert.match(r.all, /diverged.*no base/)
  assert.match(r.all, /conflict/)
})

test("update rejects an unknown slug", (dir) => {
  project(dir)
  const r = van(dir, "update", "nope")
  assert.equal(r.code, 1)
  assert.match(r.all, /unknown component/)
})

test("update rejects a slug that is not installed", (dir) => {
  project(dir)
  const r = van(dir, "update", "badge")
  assert.equal(r.code, 1)
  assert.match(r.all, /not installed/)
})

test("update copies missing lib deps", (dir) => {
  project(dir)
  van(dir, "add", "dialog")
  rmSync(join(dir, "lib/scroll-lock.js"))

  const r = van(dir, "update")
  assert.equal(r.code, 0, r.all)
  assert.ok(existsSync(join(dir, "lib/scroll-lock.js")), "missing lib file was not restored")
})

// ── summary ─────────────────────────────────────────────────────────

rmSync(scratch, { recursive: true, force: true })
console.log(`cli: ${passed} passed, ${failed} failed`)
if (failed) process.exit(1)
