/**
 * bin/van.mjs against real scratch projects.
 * Named .unit.mjs so the browser test runner runs it as a child process.
 *
 * The CLI is exercised the way a consumer runs it — spawned, with --cwd — so
 * argv parsing, exit codes and stdout are all under test, not just the
 * exported helpers.
 */

import assert from "node:assert/strict"
import { spawnSync } from "node:child_process"
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, appendFileSync, symlinkSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { fileURLToPath } from "node:url"
import { hashFile, hashBytes, readManifest, STYLESHEETS } from "../scripts/manifest.mjs"
import { createPickerState, pickerHandleKey, pickerLines, drivePicker, pickerSelection, readKey } from "../bin/van.mjs"

const repoRoot = fileURLToPath(new URL("..", import.meta.url))
const VAN = join(repoRoot, "bin", "van.mjs")
const scratch = mkdtempSync(join(tmpdir(), "van-cli-"))

let passed = 0
let failed = 0

function test(name, fn) {
  const dir = join(scratch, name.replace(/[^\w]+/g, "-"))
  mkdirSync(dir, { recursive: true })
  try {
    fn(dir)
    passed++
  } catch (err) {
    failed++
    console.error(`FAIL ${name}\n  ${err.message}`)
  }
}

/** Run van in `dir`. Colour is off so assertions can match plain strings. */
function van(dir, ...args) {
  const r = spawnSync(process.execPath, [VAN, ...args, "--cwd", dir], {
    encoding: "utf8",
    env: { ...process.env, NO_COLOR: "1" },
  })
  return { code: r.status, out: r.stdout, err: r.stderr, all: r.stdout + r.stderr }
}

/** A project with a config written straight to disk, skipping init. */
function project(dir, config = {}) {
  writeFileSync(join(dir, "van.config.json"), JSON.stringify(config, null, 2) + "\n")
  // Every stylesheet init would have copied, so a fixture is a consumer that
  // is actually up to date rather than one missing a file update must deliver.
  for (const name of STYLESHEETS) {
    mkdirSync(join(dir, "styles"), { recursive: true })
    writeFileSync(join(dir, "styles", name), readFileSync(join(repoRoot, "styles", name)))
  }
  return dir
}

/** Rewrite one recorded hash in a consumer's substrate sidecar. */
function recordHash(dir, sub, file, hash) {
  const path = join(dir, sub, ".van.json")
  const sidecar = JSON.parse(readFileSync(path, "utf8"))
  sidecar.files[file] = hash
  writeFileSync(path, JSON.stringify(sidecar, null, 2) + "\n")
}

// ── init ────────────────────────────────────────────────────────────

test("init scaffolds a buildable tree", (dir) => {
  const r = van(dir, "init")
  assert.equal(r.code, 0, r.all)

  const config = JSON.parse(readFileSync(join(dir, "van.config.json"), "utf8"))
  assert.equal(config.paths.ui, "components/ui")
  assert.ok(config.theme.brand, "no starter brand colour")

  for (const name of ["globals.css", "defaults.css", "forced-colors.css", "van.css"]) {
    assert.ok(existsSync(join(dir, "styles", name)), `styles/${name} not written`)
  }

  // The first build must already reflect the scaffolded config.
  const css = readFileSync(join(dir, "styles", "van.css"), "utf8")
  assert.match(css, /^\/\* Generated by van/)
  assert.match(css, /--primary: light-dark\(/)

  // And a rebuild is a no-op, not an error.
  assert.equal(van(dir, "build").code, 0)
})

test("init refuses to clobber an existing config", (dir) => {
  van(dir, "init")
  writeFileSync(join(dir, "van.config.json"), '{ "theme": { "radius": "1rem" } }\n')
  const r = van(dir, "init")
  assert.equal(r.code, 1)
  assert.match(r.all, /already exists/)
  assert.match(readFileSync(join(dir, "van.config.json"), "utf8"), /1rem/, "config was overwritten")
})

test("init honours components.json aliases through tsconfig paths", (dir) => {
  writeFileSync(join(dir, "tsconfig.json"), '{"compilerOptions":{"paths":{"@/*":["./src/*"]}}}\n')
  writeFileSync(
    join(dir, "components.json"),
    '{"aliases":{"ui":"@/components/ui","utils":"@/lib/utils"},"tailwind":{"css":"src/app/globals.css"}}\n',
  )
  assert.equal(van(dir, "init").code, 0)

  const config = JSON.parse(readFileSync(join(dir, "van.config.json"), "utf8"))
  assert.equal(config.paths.ui, "src/components/ui")
  assert.equal(config.paths.lib, "src/lib")
  assert.equal(config.paths.styles, "src/app")
  assert.ok(existsSync(join(dir, "src/app/globals.css")), "stylesheets ignored the detected layout")
})

// ── add ─────────────────────────────────────────────────────────────

test("add dialog pulls its lib deps", (dir) => {
  project(dir)
  const r = van(dir, "add", "dialog")
  assert.equal(r.code, 0, r.all)
  assert.ok(existsSync(join(dir, "ui/dialog/dialog.jsx")))
  assert.ok(existsSync(join(dir, "ui/dialog/dialog.css")))
  assert.ok(existsSync(join(dir, "ui/dialog/.van.json")), "no provenance sidecar")
  assert.ok(existsSync(join(dir, "lib/cn.js")), "lib/ primitive not copied")
  assert.ok(existsSync(join(dir, "lib/use-controllable-state.js")))
})

test("add alert-dialog pulls dialog transitively and its CSS import resolves", (dir) => {
  project(dir)
  assert.equal(van(dir, "add", "alert-dialog").code, 0)

  const css = readFileSync(join(dir, "ui/alert-dialog/alert-dialog.css"), "utf8")
  const imports = [...css.matchAll(/@import\s+["']\.\.\/([^/"']+)\/([^"']+)["']/g)]
  assert.ok(imports.length, "alert-dialog.css no longer @imports a sibling — update this test")
  for (const [, slug, file] of imports) {
    assert.ok(existsSync(join(dir, "ui", slug, file)), `@import ../${slug}/${file} does not resolve`)
  }
})

test("add closes the lib graph transitively", (dir) => {
  project(dir)
  // popover -> lib/use-anchor-position.js -> lib/anchor-position.js
  assert.equal(van(dir, "add", "popover").code, 0)
  assert.ok(existsSync(join(dir, "lib/use-anchor-position.js")))
  assert.ok(existsSync(join(dir, "lib/anchor-position.js")), "second-order lib dep missing")
})

test("re-add refuses an edited file, and --overwrite replaces it", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const target = join(dir, "ui/badge/badge.css")
  appendFileSync(target, "/* my edit */\n")

  const refused = van(dir, "add", "badge")
  assert.equal(refused.code, 1, refused.all)
  assert.match(refused.all, /skipped badge \(badge\.css\)/)
  assert.match(readFileSync(target, "utf8"), /my edit/, "edit was destroyed without --overwrite")

  const forced = van(dir, "add", "badge", "--overwrite")
  assert.equal(forced.code, 0, forced.all)
  assert.doesNotMatch(readFileSync(target, "utf8"), /my edit/, "--overwrite did not replace the file")

  // --force is kept as an alias of --overwrite.
  assert.equal(van(dir, "add", "badge", "--force").code, 0)
})

test("re-add overwrites a file the consumer never touched", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const target = join(dir, "ui/badge/badge.css")

  // Simulate upstream having moved on: the local file still matches what was
  // recorded at install time, but no longer matches the kit.
  appendFileSync(target, "/* pretend this came from the kit */\n")
  const sidecarPath = join(dir, "ui/badge/.van.json")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = hashFile(target)
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const r = van(dir, "add", "badge")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /badge\.css updated/)
  assert.equal(
    readFileSync(target, "utf8"),
    readFileSync(join(repoRoot, "ui/badge/badge.css"), "utf8"),
    "unmodified file was not brought up to date",
  )
})

test("add rejects a slug that is not in the registry", (dir) => {
  project(dir)
  for (const slug of ["../evil", "../../etc/passwd", "/absolute", "nope"]) {
    const r = van(dir, "add", slug)
    assert.equal(r.code, 1, `accepted ${slug}`)
    assert.match(r.all, /unknown component/)
  }
  assert.ok(!existsSync(join(dir, "..", "evil")), "wrote outside the project root")
})

test("add --dry-run writes nothing", (dir) => {
  project(dir)
  const r = van(dir, "add", "badge", "--dry-run")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /nothing written/)
  assert.ok(!existsSync(join(dir, "ui/badge")), "--dry-run wrote files")
})

// ── diff ────────────────────────────────────────────────────────────

test("diff reports an edit and exits non-zero", (dir) => {
  project(dir)
  van(dir, "add", "badge")

  const clean = van(dir, "diff")
  assert.equal(clean.code, 0, clean.all)
  assert.match(clean.out, /match(es)? kit/)

  appendFileSync(join(dir, "ui/badge/badge.css"), "/* my edit */\n")
  const dirty = van(dir, "diff")
  assert.equal(dirty.code, 1)
  assert.match(dirty.out, /badge\.css — edited locally/)
})

test("diff calls it upstream movement when the local file matches the record", (dir) => {
  project(dir)
  van(dir, "add", "badge")

  // Same simulation as the add test: local still matches what was installed,
  // so the difference against the kit is upstream's, not the consumer's.
  const target = join(dir, "ui/badge/badge.css")
  appendFileSync(target, "/* pretend this came from the kit */\n")
  const sidecarPath = join(dir, "ui/badge/.van.json")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = hashFile(target)
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const r = van(dir, "diff", "badge")
  assert.equal(r.code, 1, "a difference must still exit non-zero")
  assert.match(r.out, /badge\.css — upstream changed/)
  assert.doesNotMatch(r.out, /edited locally/)
})

test("diff flags a file that is edited locally and changed upstream", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  appendFileSync(join(dir, "ui/badge/badge.css"), "/* my edit */\n")
  const sidecarPath = join(dir, "ui/badge/.van.json")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = "sha256-something-older"
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const r = van(dir, "diff", "badge")
  assert.equal(r.code, 1)
  assert.match(r.out, /badge\.css — edited locally, and upstream changed/)
})

test("diff reports a component with no sidecar as untracked", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  rmSync(join(dir, "ui/badge/.van.json"))
  appendFileSync(join(dir, "ui/badge/badge.css"), "/* my edit */\n")

  const r = van(dir, "diff", "badge")
  assert.equal(r.code, 1)
  assert.match(r.out, /no \.van\.json/)
  assert.match(r.out, /badge\.css — not recorded/)
})

// ── list / build / usage ────────────────────────────────────────────

test("list marks installed components", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const r = van(dir, "list")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /✓ badge/)
  assert.match(r.out, /^ {2}accordion/m, "uninstalled components should not be marked")
  assert.match(r.out, /1 installed/)
})

test("build without a config fails with a pointer to init", (dir) => {
  const r = van(dir, "build")
  assert.equal(r.code, 1)
  assert.match(r.all, /van init/)
})

test("build reports config errors instead of writing", (dir) => {
  project(dir, { theme: { brand: "not-a-colour" } })
  const r = van(dir, "build")
  assert.equal(r.code, 1)
  assert.match(r.all, /oklch/)
  assert.ok(!existsSync(join(dir, "styles/van.css")), "invalid config still produced CSS")
})

test("unknown flags and commands are errors", (dir) => {
  assert.equal(van(dir, "add", "--overwirte").code, 1)
  assert.match(van(dir, "add", "--overwirte").all, /unknown flag/)
  assert.equal(van(dir, "frobnicate").code, 1)
  assert.match(van(dir, "frobnicate").all, /unknown command/)
})

test("--silent suppresses output but not errors", (dir) => {
  project(dir)
  const ok = van(dir, "add", "badge", "--silent")
  assert.equal(ok.code, 0)
  assert.equal(ok.out.trim(), "", `--silent still printed: ${ok.out}`)

  appendFileSync(join(dir, "ui/badge/badge.css"), "/* edit */\n")
  const bad = van(dir, "add", "badge", "--silent")
  assert.equal(bad.code, 1)
  assert.match(bad.err, /skipped badge/)
})

// ── framework awareness ─────────────────────────────────────────────

test("next-app projects get a use client directive", (dir) => {
  mkdirSync(join(dir, "app"), { recursive: true })
  writeFileSync(join(dir, "package.json"), '{"dependencies":{"next":"15.0.0"}}\n')

  const init = van(dir, "init")
  assert.equal(init.code, 0, init.all)
  const config = JSON.parse(readFileSync(join(dir, "van.config.json"), "utf8"))
  assert.equal(config.framework, "next-app")
  assert.equal(config.rsc, true)
  assert.equal(config.paths.styles, "app", "App Router stylesheets belong in app/")

  assert.equal(van(dir, "add", "dialog").code, 0)
  const jsx = readFileSync(join(dir, "components/ui/dialog/dialog.jsx"), "utf8")
  assert.match(jsx, /^"use client"\n\n/, "hooks-using component has no directive")
  assert.doesNotMatch(
    readFileSync(join(dir, "components/ui/dialog/dialog.css"), "utf8"),
    /use client/,
    "directive injected into CSS",
  )

  // The sidecar records the injected bytes, so nothing reads as edited.
  const diff = van(dir, "diff")
  assert.equal(diff.code, 0, diff.all)
  const readd = van(dir, "add", "dialog")
  assert.match(readd.out, /0 files written/, "re-add rewrote an unchanged component")
})

test("non-rsc projects get no directive", (dir) => {
  writeFileSync(join(dir, "package.json"), '{"devDependencies":{"vite":"6.0.0"}}\n')
  mkdirSync(join(dir, "src"), { recursive: true })
  assert.equal(van(dir, "init").code, 0)

  const config = JSON.parse(readFileSync(join(dir, "van.config.json"), "utf8"))
  assert.equal(config.framework, "vite")
  assert.equal(config.rsc, false)
  assert.equal(config.paths.styles, "src/styles")

  assert.equal(van(dir, "add", "dialog").code, 0)
  assert.doesNotMatch(readFileSync(join(dir, "components/ui/dialog/dialog.jsx"), "utf8"), /use client/)
})

test("a stateless component gets no directive even under rsc", (dir) => {
  writeFileSync(join(dir, "package.json"), '{"dependencies":{"next":"15.0.0"}}\n')
  mkdirSync(join(dir, "app"), { recursive: true })
  van(dir, "init")
  assert.equal(van(dir, "add", "separator").code, 0)
  assert.doesNotMatch(
    readFileSync(join(dir, "components/ui/separator/separator.jsx"), "utf8"),
    /use client/,
    "directive added to a component with no hooks",
  )
})

// ── update ─────────────────────────────────────────────────────────

test("update reports up-to-date when nothing changed", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const r = van(dir, "update")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /up to date/)
})

test("update overwrites upstream-changed files and bumps the manifest", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const target = join(dir, "ui/badge/badge.css")

  // Simulate: local file matches what was installed (consumer didn't edit),
  // but upstream has moved on.
  appendFileSync(target, "/* pretend this came from the kit */\n")
  const sidecarPath = join(dir, "ui/badge/.van.json")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = hashFile(target)
  sidecar.kitVersion = "0.0.1"
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const r = van(dir, "update")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /badge\.css.*updated/)

  assert.equal(
    readFileSync(target, "utf8"),
    readFileSync(join(repoRoot, "ui/badge/badge.css"), "utf8"),
    "file was not brought up to date",
  )
  const after = JSON.parse(readFileSync(sidecarPath, "utf8"))
  assert.notEqual(after.kitVersion, "0.0.1", "manifest kitVersion not bumped")
})

test("update skips files the consumer edited when upstream is unchanged", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const target = join(dir, "ui/badge/badge.css")
  appendFileSync(target, "/* my edit */\n")

  const r = van(dir, "update")
  assert.equal(r.code, 0, r.all)
  assert.match(readFileSync(target, "utf8"), /my edit/, "consumer edit was clobbered")
})

test("update --dry-run writes nothing", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const target = join(dir, "ui/badge/badge.css")
  const sidecarPath = join(dir, "ui/badge/.van.json")

  // Make it look upstream-changed.
  appendFileSync(target, "/* old kit */\n")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = hashFile(target)
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const before = readFileSync(target, "utf8")
  const r = van(dir, "update", "--dry-run")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /nothing written/)
  assert.equal(readFileSync(target, "utf8"), before, "--dry-run wrote files")
})

test("update with no args updates all installed components", (dir) => {
  project(dir)
  van(dir, "add", "badge", "separator")

  // Make both look upstream-changed.
  for (const slug of ["badge", "separator"]) {
    const css = join(dir, `ui/${slug}/${slug}.css`)
    appendFileSync(css, "/* old */\n")
    const sp = join(dir, `ui/${slug}/.van.json`)
    const s = JSON.parse(readFileSync(sp, "utf8"))
    s.files[`${slug}.css`] = hashFile(css)
    writeFileSync(sp, JSON.stringify(s, null, 2) + "\n")
  }

  const r = van(dir, "update")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /badge\.css.*updated/)
  assert.match(r.out, /separator\.css.*updated/)
})

test("update --overwrite replaces diverged files", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  const target = join(dir, "ui/badge/badge.css")
  appendFileSync(target, "/* my edit */\n")

  // Fake a different recorded hash so it looks diverged (local ≠ kit ≠ recorded).
  const sidecarPath = join(dir, "ui/badge/.van.json")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = "sha256-something-old"
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const r = van(dir, "update", "--overwrite")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /badge\.css.*overwritten/)
  assert.doesNotMatch(readFileSync(target, "utf8"), /my edit/, "edit survived --overwrite")
})

test("update reports diverged files when no git base is available", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  appendFileSync(join(dir, "ui/badge/badge.css"), "/* my edit */\n")

  const sidecarPath = join(dir, "ui/badge/.van.json")
  const sidecar = JSON.parse(readFileSync(sidecarPath, "utf8"))
  sidecar.files["badge.css"] = "sha256-something-old"
  sidecar.kitVersion = "0.0.0-nonexistent"
  writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n")

  const r = van(dir, "update")
  assert.equal(r.code, 1, "should exit non-zero on unresolvable conflicts")
  assert.match(r.all, /diverged.*no base/)
  assert.match(r.all, /conflict/)
})

test("update rejects an unknown slug", (dir) => {
  project(dir)
  const r = van(dir, "update", "nope")
  assert.equal(r.code, 1)
  assert.match(r.all, /unknown component/)
})

test("update rejects a slug that is not installed", (dir) => {
  project(dir)
  const r = van(dir, "update", "badge")
  assert.equal(r.code, 1)
  assert.match(r.all, /not installed/)
})

test("update copies missing lib deps", (dir) => {
  project(dir)
  van(dir, "add", "dialog")
  rmSync(join(dir, "lib/scroll-lock.js"))

  const r = van(dir, "update")
  assert.equal(r.code, 0, r.all)
  assert.ok(existsSync(join(dir, "lib/scroll-lock.js")), "missing lib file was not restored")
})

// ── picker state machine ───────────────────────────────────────────

test("picker: initial state starts cursor on first non-installed", (dir) => {
  const slugs = ["alpha", "beta", "gamma"]
  const installed = new Set(["alpha"])
  const state = createPickerState(slugs, installed, 10)
  assert.equal(state.cursor, 1)
  assert.equal(state.items[0].installed, true)
  assert.equal(state.items[1].installed, false)
})

test("picker: up/down wraps around", (dir) => {
  const state = createPickerState(["a", "b", "c"], new Set(), 10)
  const down3 = [state, "down", "down", "down"].reduce((s, k) =>
    typeof k === "string" ? pickerHandleKey(s, k) : s,
  )
  assert.equal(down3.cursor, 0, "down wraps to top")

  const up1 = pickerHandleKey(state, "up")
  assert.equal(up1.cursor, 2, "up wraps to bottom")
})

test("picker: space toggles selection, skips installed", (dir) => {
  const state = createPickerState(["a", "b"], new Set(["a"]), 10)
  assert.equal(state.cursor, 1)

  const toggled = pickerHandleKey(state, "space")
  assert.ok(toggled.selected.has(1))

  const untoggled = pickerHandleKey(toggled, "space")
  assert.ok(!untoggled.selected.has(1))

  const atInstalled = { ...state, cursor: 0 }
  const noToggle = pickerHandleKey(atInstalled, "space")
  assert.ok(!noToggle.selected.has(0), "installed item should not toggle")
})

test("picker: 'a' toggles all selectable", (dir) => {
  const state = createPickerState(["a", "b", "c"], new Set(["b"]), 10)
  const allOn = pickerHandleKey(state, "a")
  assert.ok(allOn.selected.has(0))
  assert.ok(!allOn.selected.has(1), "installed item not selected")
  assert.ok(allOn.selected.has(2))

  const allOff = pickerHandleKey(allOn, "a")
  assert.equal(allOff.selected.size, 0)
})

test("picker: enter sets done, escape sets cancelled", (dir) => {
  const state = createPickerState(["a"], new Set(), 10)
  const entered = pickerHandleKey(state, "enter")
  assert.ok(entered.done)
  assert.ok(!entered.cancelled)

  const escaped = pickerHandleKey(state, "escape")
  assert.ok(escaped.done)
  assert.ok(escaped.cancelled)

  const quit = pickerHandleKey(state, "q")
  assert.ok(quit.done)
  assert.ok(quit.cancelled)
})

test("picker: viewport scrolls with cursor", (dir) => {
  const state = createPickerState(["a", "b", "c", "d", "e"], new Set(), 3)
  assert.equal(state.viewStart, 0)
  assert.equal(state.viewSize, 3)

  let s = state
  s = pickerHandleKey(s, "down") // cursor 1
  s = pickerHandleKey(s, "down") // cursor 2 — still in viewport [0,3)
  assert.equal(s.viewStart, 0)
  s = pickerHandleKey(s, "down") // cursor 3 — scrolls
  assert.equal(s.viewStart, 1)
  s = pickerHandleKey(s, "down") // cursor 4
  assert.equal(s.viewStart, 2)

  s = pickerHandleKey(s, "up") // cursor 3
  s = pickerHandleKey(s, "up") // cursor 2 — scrolls back
  assert.equal(s.viewStart, 2)
  s = pickerHandleKey(s, "up") // cursor 1
  assert.equal(s.viewStart, 1)
})

test("picker: pickerLines renders correctly", (dir) => {
  const state = createPickerState(["a", "b", "c"], new Set(["b"]), 10)
  const lines = pickerLines(state)
  assert.equal(lines.length, 3)
  assert.match(lines[0], />\s+\[ \]\s+a/, "cursor on first selectable")
  assert.match(lines[1], /✓\s+b/, "installed shown with checkmark")
  assert.match(lines[2], /\[ \]\s+c/)

  const toggled = pickerHandleKey(state, "space")
  const lines2 = pickerLines(toggled)
  assert.match(lines2[0], />\s+\[x\]\s+a/, "toggled item shows [x]")
})

test("picker: non-TTY add with no args fails", (dir) => {
  project(dir)
  const r = van(dir, "add")
  assert.equal(r.code, 1)
  assert.match(r.all, /nothing to add/)
})

test("picker: --yes selects all not-installed", (dir) => {
  project(dir)
  const r = van(dir, "add", "--yes", "--dry-run")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /button/, "should include button")
  assert.match(r.out, /nothing written/)
})

// ── substrate: lib/ and styles/ ─────────────────────────────────────

test("add records lib provenance so a reinstall reads as unchanged", (dir) => {
  project(dir)
  assert.equal(van(dir, "add", "badge").code, 0)

  const sidecar = readManifest(join(dir, "lib"))
  assert.ok(sidecar, "no lib/.van.json written")
  assert.equal(sidecar.files["cn.js"], hashFile(join(dir, "lib/cn.js")))
  assert.match(van(dir, "add", "badge").out, /0 files written/, "re-add rewrote an unchanged primitive")
})

test("init records styles provenance for every stylesheet it copies", (dir) => {
  assert.equal(van(dir, "init").code, 0)

  const sidecar = readManifest(join(dir, "styles"))
  assert.ok(sidecar, "no styles/.van.json written")
  for (const name of STYLESHEETS) {
    assert.equal(sidecar.files[name], hashFile(join(dir, "styles", name)), `${name} not recorded`)
  }
})

test("update replaces an upstream-changed lib file and counts it", (dir) => {
  project(dir)
  van(dir, "add", "badge")

  // Stand in for an older kit: the consumer still holds the bytes they were
  // given, and the kit has moved on since.
  const target = join(dir, "lib/cn.js")
  const stale = "// older kit\nexport function cn() {}\n"
  writeFileSync(target, stale)
  recordHash(dir, "lib", "cn.js", hashBytes(Buffer.from(stale)))

  const r = van(dir, "update")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /lib\/cn\.js.*updated/)
  assert.match(r.out, /1 file updated/)
  assert.equal(
    readFileSync(target, "utf8"),
    readFileSync(join(repoRoot, "lib/cn.js"), "utf8"),
    "update reported success without writing the file",
  )
})

test("update leaves an edited lib file alone, and says why", (dir) => {
  project(dir)
  van(dir, "add", "badge")

  // Recorded hash still equals the kit's, so upstream has nothing to deliver.
  const target = join(dir, "lib/cn.js")
  const mine = "// mine\nexport function cn() { return \"mine\" }\n"
  writeFileSync(target, mine)

  const r = van(dir, "update")
  assert.equal(readFileSync(target, "utf8"), mine, "an edited lib file was overwritten")
  assert.match(r.out, /edited locally, upstream unchanged/)
  assert.equal(r.code, 0, "a local edit with no upstream change is not a conflict")
})

test("an unattributable lib difference is a conflict, not a silent skip", (dir) => {
  project(dir)
  van(dir, "add", "badge")

  // No recorded hash: what every install made before lib/.van.json existed
  // looks like. This is the case that used to print a dim line and exit 0.
  writeFileSync(join(dir, "lib/cn.js"), "// drifted\n")
  rmSync(join(dir, "lib/.van.json"))

  const r = van(dir, "update")
  assert.match(r.out, /lib\/cn\.js.*no recorded hash/)
  assert.match(r.all, /1 conflict/)
  assert.equal(r.code, 1, "an unresolved lib difference exited 0")
})

test("update --overwrite takes the kit copy of a drifted lib file", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  writeFileSync(join(dir, "lib/cn.js"), "// drifted\n")
  rmSync(join(dir, "lib/.van.json"))

  const r = van(dir, "update", "--overwrite")
  assert.equal(r.code, 0, r.all)
  assert.equal(
    readFileSync(join(dir, "lib/cn.js"), "utf8"),
    readFileSync(join(repoRoot, "lib/cn.js"), "utf8"),
  )
})

test("update restores a lib file the consumer deleted", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  rmSync(join(dir, "lib/cn.js"))

  const r = van(dir, "update")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /restored/)
  assert.ok(existsSync(join(dir, "lib/cn.js")), "a primitive an installed component imports stayed missing")
})

test("update refreshes a stale stylesheet so van build still passes", (dir) => {
  assert.equal(van(dir, "init").code, 0)
  assert.equal(van(dir, "add", "badge").code, 0)

  const globals = join(dir, "styles/globals.css")
  const stale = "/* older kit */\n:root { --background: white; }\n"
  writeFileSync(globals, stale)
  recordHash(dir, "styles", "globals.css", hashBytes(Buffer.from(stale)))

  const r = van(dir, "update")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /styles\/globals\.css.*updated/)
  assert.equal(
    readFileSync(globals, "utf8"),
    readFileSync(join(repoRoot, "styles/globals.css"), "utf8"),
    "styles/ was never refreshed",
  )
  assert.equal(van(dir, "build").code, 0, "a refreshed stylesheet broke van build")
})

test("diff reports lib drift instead of calling the component a match", (dir) => {
  project(dir)
  van(dir, "add", "badge")
  writeFileSync(join(dir, "lib/cn.js"), "// drifted\n")
  rmSync(join(dir, "lib/.van.json"))

  const r = van(dir, "diff")
  assert.equal(r.code, 1, "diff exited 0 with a drifted primitive on disk")
  assert.match(r.out, /lib\/cn\.js/)
  assert.doesNotMatch(r.out, /components match/)
})

test("lib files that need use client get it under rsc", (dir) => {
  writeFileSync(join(dir, "package.json"), '{"dependencies":{"next":"15.0.0"}}\n')
  mkdirSync(join(dir, "app"), { recursive: true })
  assert.equal(van(dir, "init").code, 0)
  assert.equal(van(dir, "add", "calendar").code, 0)

  // A Next project puts primitives under components/lib, not lib/.
  const libDir = join(dir, JSON.parse(readFileSync(join(dir, "van.config.json"), "utf8")).paths.lib)

  // createContext at module scope, so a Next root layout importing
  // DirectionProvider fails at build without the directive.
  assert.match(
    readFileSync(join(libDir, "direction.jsx"), "utf8"),
    /^"use client"\n\n/,
    "lib/direction.jsx shipped without its directive",
  )
  assert.doesNotMatch(readFileSync(join(libDir, "cn.js"), "utf8"), /use client/, "directive added to a plain helper")

  // The sidecar records the injected bytes, so nothing reads as edited.
  assert.match(van(dir, "add", "calendar").out, /0 files written/)
  assert.equal(van(dir, "diff").code, 0, van(dir, "diff").all)
})

// ── picker loop ─────────────────────────────────────────────────────

/**
 * Replay keystrokes through the real readKey, answering EAGAIN once before each
 * one the way a non-blocking TTY does. Composed as runPicker composes them, so
 * the retry and the loop are exercised together.
 */
function replay(keys) {
  const queue = [...keys]
  let pending = null
  const syscall = (buf) => {
    if (pending === null) {
      if (!queue.length) return 0
      pending = queue.shift()
      const err = new Error("EAGAIN: resource temporarily unavailable, read")
      err.code = "EAGAIN"
      throw err
    }
    const bytes = Buffer.from(pending)
    pending = null
    bytes.copy(buf)
    return bytes.length
  }
  return (buf) => readKey(buf, syscall)
}

test("picker: EAGAIN before a keypress does not drop it", () => {
  const buf = Buffer.alloc(16)
  let throws = 2
  const n = readKey(buf, (b) => {
    if (throws-- > 0) {
      const err = new Error("EAGAIN")
      err.code = "EAGAIN"
      throw err
    }
    return Buffer.from("a").copy(b)
  })
  assert.equal(n, 1, "one byte read after two EAGAINs")
  assert.equal(buf.subarray(0, 1).toString(), "a")
})

test("picker: a closed stdin reads as zero bytes, not an EOF throw", () => {
  const buf = Buffer.alloc(16)
  const n = readKey(buf, () => {
    const err = new Error("EOF")
    err.code = "EOF"
    throw err
  })
  assert.equal(n, 0)
})

test("picker: a read error that is not EAGAIN or EOF propagates", () => {
  assert.throws(
    () =>
      readKey(Buffer.alloc(16), () => {
        const err = new Error("EIO")
        err.code = "EIO"
        throw err
      }),
    /EIO/,
  )
})

test("picker: 'a' then enter selects every component", () => {
  const slugs = ["accordion", "button", "card", "dialog"]
  const state = createPickerState(slugs, new Set(["card"]), 10)
  const done = drivePicker(state, replay(["a", "\r"]), () => {})
  assert.equal(done.cancelled, false)
  assert.deepEqual(pickerSelection(done), ["accordion", "button", "dialog"])
})

test("picker: arrows and space select one, then enter confirms", () => {
  const state = createPickerState(["accordion", "button", "card"], new Set(), 10)
  const done = drivePicker(state, replay(["\x1b[B", " ", "\r"]), () => {})
  assert.deepEqual(pickerSelection(done), ["button"])
})

test("picker: a closed stdin cancels instead of hanging", () => {
  const state = createPickerState(["accordion", "button"], new Set(), 10)
  const done = drivePicker(state, replay([]), () => {})
  assert.equal(done.cancelled, true)
  assert.deepEqual(pickerSelection(done), [])
})

test("picker: q cancels an existing selection", () => {
  const state = createPickerState(["accordion", "button"], new Set(), 10)
  const done = drivePicker(state, replay(["a", "q"]), () => {})
  assert.deepEqual(pickerSelection(done), [])
})

test("picker: render is called once per accepted key, with that state", () => {
  const state = createPickerState(["accordion", "button"], new Set(), 10)
  const counts = []
  drivePicker(state, replay(["a", "\r"]), (s) => counts.push(s.selected.size))
  assert.deepEqual(counts, [0, 2, 2], "initial draw, after 'a', after enter")
})

// ── add --all ───────────────────────────────────────────────────────

test("add --all plans every component in the registry", (dir) => {
  project(dir)
  const r = van(dir, "add", "--all", "--dry-run")
  assert.equal(r.code, 0, r.all)
  const registry = JSON.parse(readFileSync(join(repoRoot, "registry.json"), "utf8"))
  for (const slug of Object.keys(registry.components)) {
    assert.match(r.out, new RegExp(`^${slug}$`, "m"), `${slug} missing from the plan`)
  }
  assert.match(r.out, /nothing written/)
})

test("add --all leaves an installed component's files alone", (dir) => {
  project(dir)
  assert.equal(van(dir, "add", "button").code, 0)
  const r = van(dir, "add", "--all", "--dry-run")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /^card$/m, "a component you lack is still planned")
  // button is a dependency of other components, so the closure reaches it
  // either way; what --all must not do is rewrite it.
  assert.match(r.out, /button\/button\.jsx unchanged/)
})

test("add --all a second time reports nothing left to install", (dir) => {
  project(dir)
  assert.equal(van(dir, "add", "--all").code, 0)
  const r = van(dir, "add", "--all")
  assert.equal(r.code, 1)
  assert.match(r.all, /all components are already installed/)
})

test("add --all with --overwrite includes installed components", (dir) => {
  project(dir)
  assert.equal(van(dir, "add", "button").code, 0)
  const r = van(dir, "add", "--all", "--overwrite", "--dry-run")
  assert.equal(r.code, 0, r.all)
  assert.match(r.out, /^button$/m)
})

test("add --all rejects component names alongside it", (dir) => {
  project(dir)
  const r = van(dir, "add", "--all", "button")
  assert.equal(r.code, 1)
  assert.match(r.all, /--all takes no component names/)
})

test("add with no args off a TTY names --all in the error", (dir) => {
  project(dir)
  const r = van(dir, "add")
  assert.equal(r.code, 1)
  assert.match(r.all, /--all/)
})

// ── installed entrypoint ────────────────────────────────────────────

test("van runs when argv[1] is a symlink, as npm's .bin shim makes it", (dir) => {
  // npm links node_modules/.bin/van at bin/van.mjs. resolve() does not follow
  // symlinks, so a resolved-path entrypoint check made every install a no-op.
  const link = join(dir, "van")
  symlinkSync(VAN, link)
  const r = spawnSync(process.execPath, [link, "--version"], { encoding: "utf8" })
  const version = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8")).version
  assert.equal(r.status, 0, r.stderr)
  assert.equal(r.stdout.trim(), version)
})

test("a symlinked van still runs commands, not just --version", (dir) => {
  const link = join(dir, "van")
  symlinkSync(VAN, link)
  project(dir)
  const r = spawnSync(process.execPath, [link, "list", "--cwd", dir], {
    encoding: "utf8",
    env: { ...process.env, NO_COLOR: "1" },
  })
  assert.equal(r.status, 0, r.stderr)
  assert.match(r.stdout, /components,.*installed/)
})

// ── packaged files ──────────────────────────────────────────────────

test("package.json files covers everything the CLI imports and reads", () => {
  const pkg = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8"))
  const listed = pkg.files
  assert.ok(Array.isArray(listed) && listed.length, "package.json needs a files allowlist")

  const covered = (rel) => listed.some((e) => (e.endsWith("/") ? rel.startsWith(e) : rel === e))

  // Walk the CLI's local import graph: an import npm does not pack is a
  // consumer-only crash, invisible from this checkout.
  const seen = new Set()
  const queue = ["bin/van.mjs"]
  while (queue.length) {
    const rel = queue.shift()
    if (seen.has(rel)) continue
    seen.add(rel)
    assert.ok(covered(rel), `${rel} is imported by the CLI but not in package.json files`)
    const src = readFileSync(join(repoRoot, rel), "utf8")
    const dir = rel.split("/").slice(0, -1)
    for (const m of src.matchAll(/(?:^|\n)\s*(?:import|export)[^"']*from\s*["'](\.[^"']+)["']/g)) {
      const parts = [...dir]
      for (const seg of m[1].split("/")) {
        if (seg === ".") continue
        else if (seg === "..") parts.pop()
        else parts.push(seg)
      }
      queue.push(parts.join("/"))
    }
  }
  assert.ok(seen.size > 1, "expected the CLI to import at least one local module")

  // The trees the CLI reads at run time, which no import mentions.
  for (const rel of ["registry.json", "ui/button/button.jsx", "lib/cn.js", "styles/globals.css"]) {
    assert.ok(covered(rel), `${rel} must be packed — the CLI reads it from the kit`)
  }
})

// ── summary ─────────────────────────────────────────────────────────

rmSync(scratch, { recursive: true, force: true })
console.log(`cli: ${passed} passed, ${failed} failed`)
if (failed) process.exit(1)
