/**
 * End-to-end tests for the config generator.
 * Runs in the browser test runner (Playwright).
 */

import { resolve } from "node:path"

export default async function ({ page, baseUrl, repoRoot, test, eq, near }) {
  const { generate } = await import(resolve(repoRoot, "scripts/build-theme.mjs"))

  // -------------------------------------------------------------------------
  // Determinism: byte-identical output across two runs
  // -------------------------------------------------------------------------

  const fixtureConfig = {
    theme: {
      brand: "oklch(0.55 0.2 265)",
      radius: "0.5rem",
      density: "compact",
      motion: { scale: 1.5, ease: "cubic-bezier(0.22, 1, 0.36, 1)" },
      font: { sans: "TestSans, sans-serif" },
      light: { accent: "oklch(0.93 0.05 265)" },
      dark: { accent: "oklch(0.3 0.05 265)" },
    },
    components: {
      button: {
        variants: {
          testv: {
            bg: "rgb(255, 0, 0)",
            fg: "rgb(255, 255, 255)",
          },
        },
        sizes: {
          tests: {
            height: "1.75rem",
            "padding-inline": "0.5rem",
          },
        },
      },
    },
  }

  await test("deterministic: byte-identical output", async () => {
    const css1 = generate(fixtureConfig, { root: repoRoot })
    const css2 = generate(fixtureConfig, { root: repoRoot })
    eq(css1, css2, "two runs differ")
  })

  // -------------------------------------------------------------------------
  // Empty config: no-op output
  // -------------------------------------------------------------------------

  await test("empty config produces header-only output", async () => {
    const css = generate({}, { root: repoRoot })
    const lines = css.trim().split("\n")
    eq(lines.length, 1, "expected single header line")
    eq(lines[0].startsWith("/* Generated by vanillin"), true, "missing header")
  })

  // -------------------------------------------------------------------------
  // Visual tests: inject generated CSS, check computed styles
  // -------------------------------------------------------------------------

  // Navigate to button page
  await page.goto(`${baseUrl}/#button`)
  await page.waitForSelector(".btn")

  // Inject the fixture CSS. The runner shares one page across every test file,
  // and this fixture re-declares :root tokens, so the tag must be removed
  // before the next file runs — see the cleanup at the end of this section.
  const generatedCSS = generate(fixtureConfig, { root: repoRoot })
  const styleHandle = await page.addStyleTag({ content: generatedCSS })

  // Test: generated variant applies correct background
  await test("generated variant: btn--testv background", async () => {
    const bg = await page.evaluate(() => {
      const btn = document.createElement("button")
      btn.className = "btn btn--testv"
      btn.textContent = "Test Variant"
      document.body.appendChild(btn)
      const cs = getComputedStyle(btn)
      const result = cs.backgroundColor
      btn.remove()
      return result
    })
    eq(bg, "rgb(255, 0, 0)", "background-color")
  })

  // Test: generated variant applies correct foreground
  await test("generated variant: btn--testv color", async () => {
    const fg = await page.evaluate(() => {
      const btn = document.createElement("button")
      btn.className = "btn btn--testv"
      btn.textContent = "Test Variant"
      document.body.appendChild(btn)
      const result = getComputedStyle(btn).color
      btn.remove()
      return result
    })
    eq(fg, "rgb(255, 255, 255)", "color")
  })

  // Test: generated size applies correct height
  await test("generated size: btn--tests height", async () => {
    const height = await page.evaluate(() => {
      const btn = document.createElement("button")
      btn.className = "btn btn--tests"
      btn.textContent = "Test Size"
      document.body.appendChild(btn)
      const result = parseFloat(getComputedStyle(btn).height)
      btn.remove()
      return result
    })
    near(height, 28, 1, "height") // 1.75rem = 28px at default 16px root
  })

  // Test: generated size applies correct padding
  await test("generated size: btn--tests padding-inline", async () => {
    const pl = await page.evaluate(() => {
      const btn = document.createElement("button")
      btn.className = "btn btn--tests"
      btn.textContent = "Test Size"
      document.body.appendChild(btn)
      const result = parseFloat(getComputedStyle(btn).paddingLeft)
      btn.remove()
      return result
    })
    near(pl, 8, 1, "padding-inline-start") // 0.5rem = 8px
  })

  // Test: brand derivation sets --primary
  await test("brand derivation: --primary is overridden", async () => {
    const primary = await page.evaluate(() => {
      return getComputedStyle(document.documentElement).getPropertyValue("--primary").trim()
    })
    // The generated CSS sets --primary via light-dark(), which the browser
    // resolves at computed-value time. In light mode (default), we expect the
    // light branch: oklch(0.55 0.2 265). The @property registration resolves
    // this to a computed colour — we just check it's not the default grey.
    // Default primary in light mode resolves from oklch(0.205 0 0).
    const isDefault = primary.includes("0.205") || primary === "oklch(0.205 0 0)"
    eq(isDefault, false, "primary should not be the default grey")
  })

  // Test: density-scale override
  await test("density override: --density-scale is 0.875", async () => {
    const scale = await page.evaluate(() => {
      return getComputedStyle(document.documentElement).getPropertyValue("--density-scale").trim()
    })
    eq(scale, "0.875", "density-scale")
  })

  // Test: font override
  await test("font override: --font-sans is overridden", async () => {
    const font = await page.evaluate(() => {
      return getComputedStyle(document.documentElement).getPropertyValue("--font-sans").trim()
    })
    eq(font.startsWith("TestSans"), true, "font-sans should start with TestSans")
  })

  // Remove the injected tag. Without this its :root tokens (notably
  // --density-scale: 0.875) leak into every later file, since the runner shares
  // one page and hash navigation never reloads the document.
  await styleHandle.evaluate((el) => el.remove())

  // -------------------------------------------------------------------------
  // Validation errors
  // -------------------------------------------------------------------------

  await test("validation: rejects unknown top-level key", async () => {
    let threw = false
    try {
      generate({ bogus: true }, { root: repoRoot })
    } catch {
      threw = true
    }
    eq(threw, true, "should throw")
  })

  await test("validation: rejects CSS injection in component token", async () => {
    let threw = false
    try {
      generate(
        { components: { button: { tokens: { bg: "red; --evil: 1" } } } },
        { root: repoRoot },
      )
    } catch {
      threw = true
    }
    eq(threw, true, "should throw")
  })

  await test("validation: rejects unknown component slug", async () => {
    let threw = false
    try {
      generate(
        { components: { nonexistent: { tokens: { bg: "red" } } } },
        { root: repoRoot },
      )
    } catch {
      threw = true
    }
    eq(threw, true, "should throw on unknown component")
  })
}
