/**
 * End-to-end tests for the config generator.
 * Runs in the browser test runner (Playwright).
 */

import { resolve } from "node:path"

export default async function ({ page, baseUrl, repoRoot, test, eq, near }) {
  const { generate, contrastRatio } = await import(resolve(repoRoot, "scripts/build-theme.mjs"))

  // -------------------------------------------------------------------------
  // Determinism: byte-identical output across two runs
  // -------------------------------------------------------------------------

  const fixtureConfig = {
    theme: {
      brand: "oklch(0.55 0.2 265)",
      radius: "0.5rem",
      density: "compact",
      motion: { scale: 1.5, ease: "cubic-bezier(0.22, 1, 0.36, 1)" },
      font: { sans: "TestSans, sans-serif" },
      light: { accent: "oklch(0.93 0.05 265)" },
      dark: { accent: "oklch(0.3 0.05 265)" },
    },
    components: {
      button: {
        variants: {
          testv: {
            bg: "rgb(255, 0, 0)",
            fg: "rgb(255, 255, 255)",
          },
        },
        sizes: {
          tests: {
            height: "1.75rem",
            "padding-inline": "0.5rem",
          },
        },
      },
    },
  }

  await test("deterministic: byte-identical output", async () => {
    const css1 = generate(fixtureConfig, { root: repoRoot })
    const css2 = generate(fixtureConfig, { root: repoRoot })
    eq(css1, css2, "two runs differ")
  })

  // -------------------------------------------------------------------------
  // Empty config: no-op output
  // -------------------------------------------------------------------------

  await test("empty config produces header-only output", async () => {
    const css = generate({}, { root: repoRoot })
    const lines = css.trim().split("\n")
    eq(lines.length, 1, "expected single header line")
    eq(lines[0].startsWith("/* Generated by van"), true, "missing header")
  })

  // -------------------------------------------------------------------------
  // Backward compatibility: string brand output is frozen
  // -------------------------------------------------------------------------

  // Captured from the generator before task 61. A string brand is the
  // pre-existing config surface; its output must never change.
  await test("string brand: byte-identical to pre-61 output", async () => {
    const expected =
      "/* Generated by van v0.1.0 -- do not edit by hand. */\n\n:root {\n  --primary: light-dark(oklch(0.55 0.2 265), oklch(0.85 0.17 265));\n  --primary-foreground: light-dark(oklch(0.985 0 0), oklch(0.205 0 0));\n  --ring: light-dark(oklch(0.55 0.2 265), oklch(0.85 0.17 265));\n}\n"
    eq(generate({ theme: { brand: "oklch(0.55 0.2 265)" } }, { root: repoRoot }), expected, "brand-only output changed")
  })

  await test("full fixture: byte-identical to pre-61 output", async () => {
    const expected =
      "/* Generated by van v0.1.0 -- do not edit by hand. */\n\n:root {\n  --accent: light-dark(oklch(0.93 0.05 265), oklch(0.3 0.05 265));\n  --density-scale: 0.875;\n  --font-sans: TestSans, sans-serif;\n  --motion-ease: cubic-bezier(0.22, 1, 0.36, 1);\n  --motion-scale: 1.5;\n  --primary: light-dark(oklch(0.55 0.2 265), oklch(0.85 0.17 265));\n  --primary-foreground: light-dark(oklch(0.985 0 0), oklch(0.205 0 0));\n  --radius: 0.5rem;\n  --ring: light-dark(oklch(0.55 0.2 265), oklch(0.85 0.17 265));\n}\n\n.btn--testv {\n  background-color: rgb(255, 0, 0);\n  color: rgb(255, 255, 255);\n}\n\n.btn--tests {\n  height: 1.75rem;\n  padding-inline: 0.5rem;\n}\n"
    eq(generate(fixtureConfig, { root: repoRoot }), expected, "fixture output changed")
  })

  // -------------------------------------------------------------------------
  // Contrast: every derived foreground/background pair measures >= 4.5:1
  // -------------------------------------------------------------------------

  /** Extract { light, dark } oklch strings for a --token from generated CSS. */
  function tokenModes(css, token) {
    const m = css.match(new RegExp(`--${token}: light-dark\\((oklch\\([^)]+\\)), (oklch\\([^)]+\\))\\);`))
    if (!m) throw new Error(`--${token} not found in output`)
    return { light: m[1], dark: m[2] }
  }

  const contrastBrands = [
    "oklch(0.55 0.2 265)", // well below the old 0.6 threshold
    "oklch(0.7 0.15 320)", // above it
    "oklch(0.45 0.15 145)", // dark green
    "oklch(0.3 0.1 30)", // very dark
    "oklch(0.85 0.1 90)", // very light
  ]

  for (const brand of contrastBrands) {
    await test(`contrast: derived pairs pass 4.5:1 for ${brand}`, async () => {
      const css = generate({ theme: { brand } }, { root: repoRoot })
      const bg = tokenModes(css, "primary")
      const fg = tokenModes(css, "primary-foreground")
      for (const mode of ["light", "dark"]) {
        const ratio = contrastRatio(fg[mode], bg[mode])
        eq(ratio >= 4.5, true, `${mode}: ${fg[mode]} on ${bg[mode]} measures ${ratio.toFixed(2)}:1`)
      }
    })
  }

  // -------------------------------------------------------------------------
  // Object brand: per-key derivation
  // -------------------------------------------------------------------------

  await test("object brand: string is sugar for { primary }", async () => {
    const asString = generate({ theme: { brand: "oklch(0.55 0.2 265)" } }, { root: repoRoot })
    const asObject = generate({ theme: { brand: { primary: "oklch(0.55 0.2 265)" } } }, { root: repoRoot })
    eq(asObject, asString, "object form differs from string sugar")
  })

  await test("object brand: secondary and accent derive their families", async () => {
    const css = generate(
      {
        theme: {
          brand: {
            primary: "oklch(0.55 0.2 265)",
            secondary: "oklch(0.65 0.14 190)",
            accent: "oklch(0.7 0.15 320)",
          },
        },
      },
      { root: repoRoot },
    )
    for (const key of ["primary", "secondary", "accent"]) {
      const bg = tokenModes(css, key)
      const fg = tokenModes(css, `${key}-foreground`)
      for (const mode of ["light", "dark"]) {
        const ratio = contrastRatio(fg[mode], bg[mode])
        eq(ratio >= 4.5, true, `${key} ${mode}: ${fg[mode]} on ${bg[mode]} measures ${ratio.toFixed(2)}:1`)
      }
    }
    eq(tokenModes(css, "secondary").light, "oklch(0.65 0.14 190)", "secondary light should be the brand value")
    eq(css.includes("--ring: light-dark(oklch(0.55 0.2 265)"), true, "ring derives from primary only")
  })

  await test("object brand: literal light/dark override still wins", async () => {
    const css = generate(
      {
        theme: {
          brand: { secondary: "oklch(0.65 0.14 190)" },
          light: { secondary: "oklch(0.9 0.02 190)" },
        },
      },
      { root: repoRoot },
    )
    const { light } = tokenModes(css, "secondary")
    eq(light, "oklch(0.9 0.02 190)", "literal override lost to derivation")
  })

  await test("neutral brand: tints the grey families, pairs pass 4.5:1", async () => {
    const css = generate({ theme: { brand: { neutral: "oklch(0.55 0.02 265)" } } }, { root: repoRoot })
    for (const key of ["secondary", "muted", "accent"]) {
      const bg = tokenModes(css, key)
      const fg = tokenModes(css, `${key}-foreground`)
      for (const mode of ["light", "dark"]) {
        eq(bg[mode].endsWith(" 0.02 265)"), true, `${key} ${mode} should carry the neutral hue: ${bg[mode]}`)
        const ratio = contrastRatio(fg[mode], bg[mode])
        eq(ratio >= 4.5, true, `${key} ${mode}: ${fg[mode]} on ${bg[mode]} measures ${ratio.toFixed(2)}:1`)
      }
    }
    // Lightness ramp is the kit's, not the neutral colour's
    eq(tokenModes(css, "secondary").light.startsWith("oklch(0.97 "), true, "light tint keeps ramp lightness")
    eq(tokenModes(css, "secondary").dark.startsWith("oklch(0.269 "), true, "dark tint keeps ramp lightness")
  })

  await test("neutral brand: chroma is capped", async () => {
    const css = generate({ theme: { brand: { neutral: "oklch(0.55 0.2 265)" } } }, { root: repoRoot })
    eq(tokenModes(css, "muted").light, "oklch(0.97 0.03 265)", "chroma should cap at 0.03")
  })

  await test("neutral brand: explicit secondary wins over the tint", async () => {
    const css = generate(
      { theme: { brand: { neutral: "oklch(0.55 0.02 265)", secondary: "oklch(0.65 0.14 190)" } } },
      { root: repoRoot },
    )
    eq(tokenModes(css, "secondary").light, "oklch(0.65 0.14 190)", "explicit key lost to neutral tint")
    eq(tokenModes(css, "muted").light, "oklch(0.97 0.02 265)", "muted should still be tinted")
  })

  await test("contrast: mid-range brand with no passing foreground throws", async () => {
    // oklch(0.58 0 0) fails both candidates (best measures ~4.18:1);
    // the old threshold silently picked white here.
    let msg = ""
    try {
      generate({ theme: { brand: "oklch(0.58 0 0)" } }, { root: repoRoot })
    } catch (e) {
      msg = e.message
    }
    eq(msg.includes("4.5:1"), true, "should throw a contrast error")
  })

  // -------------------------------------------------------------------------
  // Visual tests: inject generated CSS, check computed styles
  // -------------------------------------------------------------------------

  // Navigate to button page
  await page.goto(`${baseUrl}/#button`)
  await page.waitForSelector(".btn")

  // Inject the fixture CSS. The runner shares one page across every test file,
  // and this fixture re-declares :root tokens, so the tag must be removed
  // before the next file runs — see the cleanup at the end of this section.
  const generatedCSS = generate(fixtureConfig, { root: repoRoot })
  const styleHandle = await page.addStyleTag({ content: generatedCSS })

  // Test: generated variant applies correct background
  await test("generated variant: btn--testv background", async () => {
    const bg = await page.evaluate(() => {
      const btn = document.createElement("button")
      btn.className = "btn btn--testv"
      btn.textContent = "Test Variant"
      document.body.appendChild(btn)
      const cs = getComputedStyle(btn)
      const result = cs.backgroundColor
      btn.remove()
      return result
    })
    eq(bg, "rgb(255, 0, 0)", "background-color")
  })

  // Test: generated variant applies correct foreground
  await test("generated variant: btn--testv color", async () => {
    const fg = await page.evaluate(() => {
      const btn = document.createElement("button")
      btn.className = "btn btn--testv"
      btn.textContent = "Test Variant"
      document.body.appendChild(btn)
      const result = getComputedStyle(btn).color
      btn.remove()
      return result
    })
    eq(fg, "rgb(255, 255, 255)", "color")
  })

  // Test: generated size applies correct height
  await test("generated size: btn--tests height", async () => {
    const height = await page.evaluate(() => {
      const btn = document.createElement("button")
      btn.className = "btn btn--tests"
      btn.textContent = "Test Size"
      document.body.appendChild(btn)
      const result = parseFloat(getComputedStyle(btn).height)
      btn.remove()
      return result
    })
    near(height, 28, 1, "height") // 1.75rem = 28px at default 16px root
  })

  // Test: generated size applies correct padding
  await test("generated size: btn--tests padding-inline", async () => {
    const pl = await page.evaluate(() => {
      const btn = document.createElement("button")
      btn.className = "btn btn--tests"
      btn.textContent = "Test Size"
      document.body.appendChild(btn)
      const result = parseFloat(getComputedStyle(btn).paddingLeft)
      btn.remove()
      return result
    })
    near(pl, 8, 1, "padding-inline-start") // 0.5rem = 8px
  })

  // Test: brand derivation sets --primary
  await test("brand derivation: --primary is overridden", async () => {
    const primary = await page.evaluate(() => {
      return getComputedStyle(document.documentElement).getPropertyValue("--primary").trim()
    })
    // The generated CSS sets --primary via light-dark(), which the browser
    // resolves at computed-value time. In light mode (default), we expect the
    // light branch: oklch(0.55 0.2 265). The @property registration resolves
    // this to a computed colour — we just check it's not the default grey.
    // Default primary in light mode resolves from oklch(0.205 0 0).
    const isDefault = primary.includes("0.205") || primary === "oklch(0.205 0 0)"
    eq(isDefault, false, "primary should not be the default grey")
  })

  // Test: density-scale override
  await test("density override: --density-scale is 0.875", async () => {
    const scale = await page.evaluate(() => {
      return getComputedStyle(document.documentElement).getPropertyValue("--density-scale").trim()
    })
    eq(scale, "0.875", "density-scale")
  })

  // Test: font override
  await test("font override: --font-sans is overridden", async () => {
    const font = await page.evaluate(() => {
      return getComputedStyle(document.documentElement).getPropertyValue("--font-sans").trim()
    })
    eq(font.startsWith("TestSans"), true, "font-sans should start with TestSans")
  })

  // Remove the injected tag. Without this its :root tokens (notably
  // --density-scale: 0.875) leak into every later file, since the runner shares
  // one page and hash navigation never reloads the document.
  await styleHandle.evaluate((el) => el.remove())

  // -------------------------------------------------------------------------
  // Validation errors
  // -------------------------------------------------------------------------

  await test("validation: rejects unknown top-level key", async () => {
    let threw = false
    try {
      generate({ bogus: true }, { root: repoRoot })
    } catch {
      threw = true
    }
    eq(threw, true, "should throw")
  })

  await test("validation: rejects CSS injection in component token", async () => {
    let threw = false
    try {
      generate(
        { components: { button: { tokens: { bg: "red; --evil: 1" } } } },
        { root: repoRoot },
      )
    } catch {
      threw = true
    }
    eq(threw, true, "should throw")
  })

  await test("validation: rejects unknown component slug", async () => {
    let threw = false
    try {
      generate(
        { components: { nonexistent: { tokens: { bg: "red" } } } },
        { root: repoRoot },
      )
    } catch {
      threw = true
    }
    eq(threw, true, "should throw on unknown component")
  })
}
