import { readFileSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"

/*
 * The order wizard has a route of its own (#order) and a standalone entry
 * (site/order.html); it is no longer a page inside the console mock. Five
 * steps, a live price rail, one table under the form. The order persists in
 * localStorage and in the share link, so every test that depends on the
 * defaults starts from a cleared store.
 */
const SSH_KEY = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExample you@laptop"

export default async function run({ page, baseUrl, test, eq, near }) {
  const frame = page.locator(".ck-console")
  const order = frame.locator(".ck-order")
  const rect = (locator) => locator.evaluate((el) => el.getBoundingClientRect().toJSON())
  const style = (locator, prop) => locator.evaluate((el, p) => getComputedStyle(el)[p], prop)
  const texts = async (locator, sep = " | ") => (await locator.allTextContents()).join(sep)
  // Kit controls transition their colours, so a colour read right after a
  // click is the transition's start value (docs/QUIRKS.md). Wait it out.
  const settled = () =>
    page.waitForFunction(() => !document.getAnimations().some((a) => a instanceof CSSTransition))
  // Computed colour of `var(--token)` resolved inside the order page. The
  // console frame inverts --live-value-up/-down, so probe the order, not it.
  const orderColour = (token) =>
    page.evaluate((t) => {
      const el = document.querySelector(".ck-order")
      const probe = document.createElement("span")
      probe.style.color = `var(${t})`
      el.appendChild(probe)
      const c = getComputedStyle(probe).color
      probe.remove()
      return c
    }, token)
  const clearStore = () => page.evaluate(() => localStorage.clear())
  // A real navigation: the site is an SPA, and a goto that only changes the
  // hash would leave the mounted order (and its store writes) in place.
  const arrive = async (hash = "#order") => {
    await page.goto("about:blank")
    await page.goto(`${baseUrl}/${hash}`)
    await page.waitForSelector('.ck-console[data-pg="order"] .ck-order')
  }
  // A fresh order from the defaults: the store is cleared, then the page
  // re-reads it.
  const reset = async () => {
    await arrive()
    await clearStore()
    await arrive()
  }
  const tab = (label) => order.locator(".ck-order-tabs .tabs-trigger", { hasText: label })
  const panel = (step) => order.locator(`.ck-order-panel[data-step="${step}"]`)
  const goTab = async (label, step) => {
    await tab(label).click()
    await panel(step).waitFor()
  }
  const total = order.locator(".ck-order-rail .ck-order-total-live")
  const glow = order.locator(".ck-order-rail .ck-order-total-glow")
  const sliderInput = (field) => order.locator(`.ck-slider-row[data-field="${field}"] .ck-slider-input`)
  const setSlider = async (field, value) => {
    const input = sliderInput(field)
    await input.fill(String(value))
    await input.press("Enter")
  }
  const fillKey = async () => {
    await goTab("Infrastructure", "infrastructure")
    const key = order.locator(".ck-order-key")
    await key.fill(SSH_KEY)
    await key.blur()
  }
  const noneLeft = (selector) => page.waitForFunction((s) => document.querySelectorAll(s).length === 0, selector)
  const toastWith = (text) =>
    page.waitForFunction((t) => [...document.querySelectorAll(".toast")].some((el) => el.textContent.includes(t)), text)

  await reset()

  await test("the wizard owns the page: five numbered steps, the brand's tokens in both schemes, a way back", async () => {
    eq(await frame.locator(".ck-topbar").count(), 0, "the console top bar is still mounted")
    eq(await frame.locator(".ck-pri, .ck-sec").count(), 0, "the console rails are still mounted")
    eq(await frame.getAttribute("data-pg"), "order")
    eq(await frame.locator(".ck-page-title").textContent(), "New virtual Data Center")

    const steps = order.locator(".ck-order-tabs .tabs-trigger")
    eq(await texts(steps.locator(".ck-order-step-num"), ""), "12345")
    eq(
      (await steps.evaluateAll((els) => els.map((el) => el.textContent.replace(/^\d/, "")))).join(" | "),
      "Location | Infrastructure | Storage | Add-ons | Review",
    )
    eq((await steps.evaluateAll((els) => els.map((el) => el.dataset.state))).join(","), "active,inactive,inactive,inactive,inactive")
    eq(await order.locator(".ck-order-panel").count(), 1, "only the active step is mounted")
    eq(await order.locator(".ck-order-step-title").textContent(), "Choose a location")
    eq(await order.locator(".ck-order-step-flag").count(), 0, "nothing is flagged before anything is touched")
    const [listBox, bodyBox] = await Promise.all([rect(order.locator(".ck-order-tabs .tabs-list")), rect(order.locator(".ck-order-body"))])
    near(listBox.width, bodyBox.width, 1, "the strip spans the page")

    // The rail: name, site, the live total and its hourly twin.
    eq(await order.locator(".ck-order-rail-name code").textContent(), "vdc-01")
    eq(await order.locator(".ck-order-rail-name > span").textContent(), "DFW Cage 6")
    eq(await total.textContent(), "$605.00")
    eq(await order.locator(".ck-order-rail .ck-order-total-hr").textContent(), "$0.829")
    eq(await order.locator(".ck-order-rail-issues").count(), 0, "an untouched key is not yet an error")
    eq(await order.locator(".ck-order-rail .ck-order-continue").textContent(), "Continue to Infrastructure")
    eq(await style(order.locator(".ck-order-rail"), "position"), "sticky")
    eq(await order.locator(".ck-order-cart-count").textContent(), "1 vDC")
    eq(await order.locator(".ck-order-cart-total").textContent(), "$605.00/mo")
    eq(await order.locator(".ck-order-rail-order strong").textContent(), "$605.00/mo")

    // Brand tokens: orange is the primary and marks the chosen option; blue
    // is the ring. Blue shifts to Light Blue on dark, orange holds.
    await settled()
    const orange = await orderColour("--ck-orange")
    const blue = await orderColour("--ck-blue")
    eq(orange !== blue, true, "orange and blue are two hues")
    eq(await orderColour("--primary"), orange, "orange is --primary")
    eq(await orderColour("--ring"), blue, "blue is the ring")
    eq(await style(order.locator('.ck-site[data-state="checked"]'), "borderTopColor"), orange, "the chosen site is outlined in orange")
    eq(await style(order.locator('.ck-order-tabs .tabs-trigger[data-state="active"] .ck-order-step-num'), "backgroundColor"), orange)
    eq(await style(order.locator(".ck-order-rail .ck-order-continue"), "backgroundColor"), orange, "the primary button is orange")
    eq(await orderColour("--live-value-up"), blue, "a rising price is blue here")
    eq(await orderColour("--live-value-down"), orange, "a falling price is orange here")
    const lightBg = await style(frame, "backgroundColor")
    await page.evaluate(() => document.documentElement.classList.toggle("dark", true))
    await settled()
    eq(await orderColour("--ck-orange"), orange, "orange is the same in both schemes")
    eq((await orderColour("--ck-blue")) !== blue, true, "blue lightens on dark")
    eq(await orderColour("--primary-foreground"), "oklch(0.99 0 0)", "orange carries white text on dark too")
    eq((await style(frame, "backgroundColor")) !== lightBg, true, "the page turns dark")
    await page.evaluate(() => document.documentElement.classList.toggle("dark", false))
    await settled()
    eq(await style(frame, "backgroundColor"), lightBg)

    const back = order.locator(".ck-order-back")
    eq(await back.evaluate((el) => el.tagName), "A", "the way back is a link")
    eq(await back.textContent(), "Console")
    eq(await back.getAttribute("href"), "#console")
  })

  await test("the path is remembered, a workload picks the plan, image and storage, and the skip lands on Size", async () => {
    eq(await order.locator('.ck-path .toggle-group-item[data-state="on"] .ck-preset-name').textContent(), "Custom")
    eq(await order.getAttribute("data-path"), "custom")
    await order.locator(".ck-path .ck-preset", { hasText: "Quick Deploy" }).click()
    await frame.locator('.ck-order[data-path="quick"]').waitFor()
    eq(await page.evaluate(() => localStorage.getItem("vanillin.order.path")), "quick")
    eq(await order.locator(".ck-order-rail .ck-order-continue").textContent(), "Continue to Review", "Quick Deploy skips from Location to Review")
    await arrive()
    eq(await order.getAttribute("data-path"), "quick", "the path survives a reload")
    await order.locator(".ck-path .ck-preset", { hasText: "Custom" }).click()
    await frame.locator('.ck-order[data-path="custom"]').waitFor()
    eq(await order.locator(".ck-order-rail .ck-order-continue").textContent(), "Continue to Infrastructure")

    const cards = order.locator(".ck-workload")
    eq(await texts(cards.locator(".ck-workload-name")), "General VM | Website | Development | Database | GPU | Windows")
    eq(await order.locator('.ck-workload[data-state="checked"] .ck-workload-name').textContent(), "General VM")
    eq(await order.locator('.ck-workload[data-state="checked"] .ck-workload-plan').textContent(), "Plan M · 20 GHz · 64 GB")
    await cards.filter({ hasText: "Database" }).click()
    await order.locator('.ck-workload[data-state="checked"]', { hasText: "Database" }).waitFor()
    // L (60 GHz, 192 GB) and 500 GB of Tier 3 + 250 GB of Tier 4.
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$1,710.00" }).waitFor()
    await order.locator('.ck-order-rail .ck-order-total-glow[data-last-trend="up"]').waitFor()
    await settled()
    eq(await style(total, "color"), await orderColour("--ck-blue"), "a rising total is blue")
    eq(await order.locator(".ck-order-cart-total").textContent(), "$1,710.00/mo")

    await goTab("Infrastructure", "infrastructure")
    eq(await order.locator('.ck-plan[data-state="checked"] .ck-plan-name').textContent(), "L")
    eq(await order.locator(".ck-plan[data-recommended] .ck-plan-name").textContent(), "L")
    eq(await order.locator(".ck-plan[data-recommended] .ck-recommended-reason").textContent(), "L keeps the working set in RAM; Tier 3 and Tier 4 give the log and the tablespace their IOPS.")
    eq(await order.locator('.ck-software-list .ck-option:has(.radio-group-item[data-state="checked"]) .ck-option-name').textContent(), "Rocky Linux 9.3Popular")
    eq(await sliderInput("cpu").inputValue(), "60")
    eq(await sliderInput("ram").inputValue(), "192")
    eq(await order.locator(".ck-order-draw").textContent(), "The machines in this vDC draw 8 GHz of 60 and 16 GB of 192.", "the workload re-sized the machine too")

    await goTab("Location", "location")
    await cards.filter({ hasText: "General VM" }).click()
    // General's own mix is 250 + 250 GB, not the form's 500 + 250 default.
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$592.50" }).waitFor()
    await order.locator('.ck-order-rail .ck-order-total-glow[data-last-trend="down"]').waitFor()
    await settled()
    eq(await style(total, "color"), await orderColour("--ck-orange"), "a falling total is orange")

    await order.locator(".ck-order-skip").click()
    await panel("infrastructure").waitFor()
    eq(await order.locator('[data-section="size"]').count(), 1, "the skip lands on Size")
  })

  await test("users pick the recommended site, Use it follows it, the comparison folds open, and a bad name errors beside its input", async () => {
    await reset()
    eq(await order.locator('.ck-users .toggle-group-item[data-state="on"]').textContent(), "Everywhere, or not sure")
    eq(await order.locator(".ck-recommendation-title").textContent(), "We recommend DFW Cage 6")
    eq(await order.locator(".ck-recommendation[data-followed]").count(), 1, "the default already follows the recommendation")
    eq(await order.locator(".ck-recommendation-use").count(), 0)
    eq(await texts(order.locator(".ck-site-name")), "DFW Cage 6Recommended | Chicago Cage 6 | SLC Cage 6")
    eq(await texts(order.locator(".ck-site-city")), "Plano, TX · sales tax TX 8.25% | Chicago, IL · sales tax IL 10.25% | Salt Lake City, UT · sales tax UT 7.25%")

    await order.locator(".ck-users .toggle-group-item", { hasText: "Mountain West" }).click()
    await order.locator(".ck-recommendation-title", { hasText: "SLC Cage 6" }).waitFor()
    eq(await order.locator(".ck-recommendation[data-followed]").count(), 0, "DFW is still chosen, so the recommendation is not followed")
    eq(await order.locator(".ck-site[data-recommended] .ck-site-name").textContent(), "SLC Cage 6Recommended")
    eq(await order.locator(".ck-recommendation .ck-option-desc").textContent(), "SLC is the closest site to Denver, Phoenix and the Bay Area, and it is out of the hurricane belt.")
    await order.locator(".ck-recommendation-use").click()
    await order.locator(".ck-recommendation[data-followed]").waitFor()
    eq(await order.locator('.ck-site[data-state="checked"] .ck-site-name').textContent(), "SLC Cage 6Recommended")
    eq(await order.locator(".ck-order-rail-name > span").textContent(), "SLC Cage 6")
    eq(await order.locator(".ck-order-name .input-group-text").textContent(), "slc.acme.cloud")
    await settled()
    eq(await style(order.locator('.ck-site[data-state="checked"]'), "borderTopColor"), await orderColour("--ck-orange"))

    // Compare sites: a table behind a disclosure, the chosen row tinted.
    const trigger = order.locator('[data-disclosure="compare-sites"] .ck-disclosure-trigger')
    eq(await trigger.getAttribute("data-state"), "closed")
    eq(await order.locator(".ck-compare").isVisible(), false)
    await trigger.click()
    await order.locator(".ck-compare").waitFor()
    eq(await trigger.getAttribute("data-state"), "open")
    eq(await texts(order.locator(".ck-compare thead th")), "Site | Texas and the South | Midwest and Northeast | Mountain West and Pacific | New capacity | Seismic risk | Sales tax")
    eq(await order.locator(".ck-compare tbody tr").count(), 3)
    eq(await texts(order.locator(".ck-compare tbody tr").first().locator("td")), "8 ms | 24 ms | 32 ms | same day | low | TX 8.25%")
    eq(await order.locator('.ck-compare tr[data-state="checked"] th').textContent(), "SLC Cage 6recommended")
    eq(await order.locator(".ck-compare .ck-chip").count(), 1, "one recommended chip")
    eq(await style(order.locator(".ck-compare-wrap"), "overflowX"), "auto")

    // The name: no error while typing, one beside the input after blur, and
    // nothing else on the page moves.
    const name = order.locator("#ck-order-name")
    await name.fill("")
    eq(await order.locator('.ck-order-error[data-field="name"]').count(), 0, "typing is not yet a decision")
    await name.blur()
    const error = order.locator('.ck-order-error[data-field="name"]')
    await error.waitFor()
    eq(await error.textContent(), "Give the vDC a name.")
    eq(await name.getAttribute("aria-invalid"), "true")
    const [inputBox, errorBox] = await Promise.all([rect(order.locator(".ck-order-name")), rect(error)])
    eq(errorBox.y > inputBox.y && errorBox.y - (inputBox.y + inputBox.height) < 80, true, `the error sits under its input (${inputBox.y} → ${errorBox.y})`)
    eq(await tab("Location").locator(".ck-order-step-flag").textContent(), "1", "the tab carries the count")
    eq(await texts(order.locator(".ck-order-rail-issues .ck-order-issue")), "Give the vDC a name.")
    eq(await order.locator(".ck-order-rail-name code").textContent(), "unnamed")
    eq(await order.locator('.ck-site[data-state="checked"] .ck-site-name').textContent(), "SLC Cage 6Recommended", "the site is untouched")
    eq(await order.locator(".ck-compare").isVisible(), true, "the disclosure stayed open")
    await name.fill("Vdc_01")
    await name.blur()
    await order.locator('.ck-order-error[data-field="name"]', { hasText: "Lower-case" }).waitFor()
    await name.fill("vdc-01")
    await name.blur()
    await noneLeft('.ck-order-error[data-field="name"]')
    eq(await order.locator(".ck-order-step-flag").count(), 0)
  })

  await test("infrastructure: software tabs, plan cards priced hourly, the slider bound to its input both ways, deltas on the uplinks, the key", async () => {
    await reset()
    await order.locator(".ck-order-panel .ck-order-footer .ck-order-continue").click()
    await panel("infrastructure").waitFor()
    eq(await order.locator(".ck-order-step-title").textContent(), "Size the infrastructure")

    // Software: four tabs with counts, popular and recent first.
    const softTabs = order.locator(".ck-software .tabs-trigger")
    eq((await softTabs.evaluateAll((els) => els.map((el) => el.firstChild.textContent))).join(" | "), "Operating systems | Applications | Snapshots | Custom images")
    eq(await texts(softTabs.locator(".ck-software-count")), "5 | 4 | 0 | 1")
    const options = order.locator(".ck-software-list .ck-option")
    eq(await options.count(), 5)
    eq(await texts(options.first().locator(".ck-chip")), "Recent | Popular")
    eq(await order.locator('.ck-software-list .ck-option:has(.radio-group-item[data-state="checked"]) .ck-option-name').textContent(), "Ubuntu 24.04 LTSRecentPopular")
    await softTabs.filter({ hasText: "Snapshots" }).click()
    await order.locator(".ck-software-empty").waitFor()
    eq(await order.locator(".ck-software-empty .empty-title").textContent(), "No snapshots yet")
    await softTabs.filter({ hasText: "Custom images" }).click()
    await order.locator(".ck-software-list").waitFor()
    eq(await order.locator(".ck-software-list .ck-option-meta").textContent(), "$20.00 per machine", "the licence is priced on the card")
    await softTabs.filter({ hasText: "Operating systems" }).click()

    // Plans: hourly first, monthly as the estimate, the workload's pick marked.
    const plans = order.locator(".ck-plan")
    eq(await texts(plans.locator(".ck-plan-name")), "S | M | L | XL | Custom")
    eq(await order.locator('.ck-plan[data-state="checked"] .ck-plan-name').textContent(), "M")
    eq(await order.locator(".ck-plan[data-recommended] .ck-plan-name").textContent(), "M")
    eq(await texts(plans.locator(".ck-plan-price strong")), "$0.351 | $0.712 | $2.137 | $5.589 | $0.712")
    eq(await texts(plans.locator(".ck-plan-monthly")), "$256.00/mo estimate | $520.00/mo estimate | $1,560.00/mo estimate | $4,080.00/mo estimate | $520.00/mo estimate")
    eq(await order.locator(".ck-plan--custom .ck-plan-spec").textContent(), "20 GHz · 64 GB")
    await plans.filter({ has: page.locator(".ck-plan-name", { hasText: /^XL$/ }) }).click()
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$4,165.00" }).waitFor()
    eq(await sliderInput("cpu").inputValue(), "120")
    eq(await sliderInput("ram").inputValue(), "512")
    eq(await texts(order.locator('[data-section="size"] .ck-slider-price')), "$240.00/mo | $3,840.00/mo")
    await order.locator('.ck-order-rail .ck-order-total-glow[data-last-trend="up"]').waitFor()
    await settled()
    eq(await style(total, "color"), await orderColour("--ck-blue"), "up is blue")

    // Track → input: End on the thumb fills the input and the plan reads Custom.
    const cpuThumb = order.locator('.slider[aria-label="CPU pool"] .slider-thumb')
    await cpuThumb.focus()
    await page.keyboard.press("End")
    await order.locator(".ck-slider-price", { hasText: "$400.00/mo" }).waitFor()
    eq(await sliderInput("cpu").inputValue(), "200")
    eq(await order.locator('.ck-plan[data-state="checked"] .ck-plan-name').textContent(), "Custom")
    eq(await order.locator(".ck-plan--custom .ck-plan-spec").textContent(), "200 GHz · 512 GB")
    // Input → track: a typed figure snaps to the step and moves the thumb.
    await setSlider("cpu", 21)
    await order.locator(".ck-slider-price", { hasText: "$44.00/mo" }).waitFor()
    eq(await sliderInput("cpu").inputValue(), "22", "21 snaps to the 2 GHz grid")
    eq(await cpuThumb.getAttribute("aria-valuenow"), "22")
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$3,969.00" }).waitFor()
    await order.locator('.ck-order-rail .ck-order-total-glow[data-last-trend="down"]').waitFor()
    await settled()
    eq(await style(total, "color"), await orderColour("--ck-orange"), "down is orange")
    await setSlider("cpu", "")
    eq(await sliderInput("cpu").inputValue(), "22", "an emptied box falls back to the value")
    await plans.filter({ has: page.locator(".ck-plan-name", { hasText: /^M$/ }) }).click()
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$605.00" }).waitFor()
    eq(await order.locator(".ck-order-draw").textContent(), "The machines in this vDC draw 2 GHz of 20 and 4 GB of 64.")
    eq(await order.locator(".ck-order-draw[data-over]").count(), 0)

    // Network: IPv4 is the one thing that costs; the uplinks carry deltas.
    eq(await texts(order.locator('.ck-slider-row[data-field="ips"] .ck-slider-tick')), "0 | 8 | 16 | 24 | 32")
    eq(await texts(order.locator(".ck-network-facts .ck-order-line-name")), "IPv6 /64 | Edge firewall")
    eq(await texts(order.locator(".ck-network-facts .ck-order-line-price")), "$0.00/mo | $0.00/mo")
    await order.locator('[data-disclosure="advanced-network"] .ck-disclosure-trigger').click()
    const uplinks = order.locator('[data-disclosure="advanced-network"] .ck-presets .ck-preset')
    await uplinks.first().waitFor()
    eq(await texts(uplinks.locator(".ck-preset-meta")), "base tier | +$60.00/mo | +$220.00/mo")
    eq(await uplinks.nth(1).locator('.ck-delta[data-sign="up"]').count(), 1)
    await uplinks.filter({ hasText: "1 Gbps" }).click()
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$825.00" }).waitFor()
    await uplinks.filter({ hasText: "10 Mbps" }).click()
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$605.00" }).waitFor()

    // Access: Continue surfaces the empty key; a bad key says why; a good one clears it.
    eq(await order.locator('.ck-order-error[data-field="access"]').count(), 0)
    await order.locator(".ck-order-panel .ck-order-footer .ck-order-continue").click()
    await panel("storage").waitFor()
    eq(await tab("Infrastructure").locator(".ck-order-step-flag").textContent(), "1", "Continue touched the step's fields")
    eq(await texts(order.locator(".ck-order-rail-issues .ck-order-issue")), "Paste a public key, or switch to a password.")
    await order.locator(".ck-order-rail-issues .ck-order-issue").click()
    await panel("infrastructure").waitFor()
    eq(await order.locator('.ck-order-error[data-field="access"]').textContent(), "Paste a public key, or switch to a password.")
    const key = order.locator(".ck-order-key")
    await key.fill("hello")
    await key.blur()
    await order.locator('.ck-order-error[data-field="access"]', { hasText: "does not look like" }).waitFor()
    await key.fill(SSH_KEY)
    await key.blur()
    await noneLeft('.ck-order-error[data-field="access"]')
    eq(await order.locator(".ck-order-rail-issues").count(), 0)
    await order.locator('.ck-segments[aria-label="Access method"] .toggle-group-item', { hasText: "Password" }).click()
    await order.locator("#ck-order-password").waitFor()
    await order.locator("#ck-order-password").fill("short")
    await order.locator("#ck-order-password").blur()
    await order.locator('.ck-order-error[data-field="access"]', { hasText: "Twelve characters" }).waitFor()
    await order.locator('.ck-segments[aria-label="Access method"] .toggle-group-item', { hasText: "SSH key" }).click()
    await order.locator(".ck-order-key").waitFor()
    eq(await order.locator(".ck-order-key").inputValue(), SSH_KEY, "the key was kept behind the switch")
    eq(await order.locator(".ck-marker").count(), 4, "included features are markers")
  })

  await test("storage: ticks, prices, the mix bar and the spec card; zero storage blocks protection and the boot volumes", async () => {
    await reset()
    await goTab("Storage", "storage")
    eq(await order.locator(".ck-slider-row .slider").count(), 4, "four tiers")
    eq(await texts(order.locator(".ck-slider-label .ck-hint")), "Tier 1 | Tier 2 | Tier 3 | Tier 4")
    eq(await texts(order.locator(".ck-slider-price")), "$25.00/mo | $20.00/mo | $0.00/mo | $0.00/mo")
    eq(await texts(order.locator(".ck-slider-row").first().locator(".ck-slider-tick")), "0 | 2,500 | 5,000 | 7,500 | 10k")
    const trackBox = await rect(order.locator(".ck-slider-row").first().locator(".slider-track"))
    const lastTick = await rect(order.locator(".ck-slider-row").first().locator(".ck-slider-tick").last())
    near(lastTick.x + lastTick.width / 2, trackBox.x + trackBox.width, 2, "the last tick sits under the track's end")
    eq(await order.locator(".ck-storage-mix-total").textContent(), "750 GB · $45.00/mo")
    eq(await order.locator(".ck-storage-mix-seg").count(), 2, "only tiers holding storage draw a segment")
    eq(await order.locator(".ck-order-draw").textContent(), "Boot volumes for the machines below take 40 GB of the 750 GB provisioned.")
    await settled()
    eq(await style(order.locator(".slider-range").first(), "backgroundColor"), await orderColour("--ck-orange"), "the filled range is orange")

    eq(await page.locator(".ck-spec-card:popover-open").count(), 0)
    await order.locator(".ck-slider-label .ck-hint", { hasText: "Tier 3" }).hover()
    const spec = page.locator(".ck-spec-card:popover-open")
    await spec.waitFor()
    eq(await spec.locator(".ck-spec-title").textContent(), "Tier 3 · SSD")
    eq(await texts(spec.locator(".ck-spec-row dd")), "16,000 | 1 ms | $0.12 per GB")
    await page.mouse.move(0, 0)
    await noneLeft(".ck-spec-card:popover-open")

    await setSlider("storage-t1", 0)
    await setSlider("storage-t2", 0)
    await order.locator(".ck-storage-mix-total", { hasText: "0 GB · $0.00/mo" }).waitFor()
    eq(await order.locator(".ck-storage-mix-seg").count(), 0)
    eq(await order.locator(".ck-order-draw[data-over]").count(), 1, "the boot volumes no longer fit")
    eq(await order.locator('.ck-order-error[data-field="storage"]').textContent(), "Machines need a boot volume: put storage on at least one tier.")
    eq(await tab("Storage").locator(".ck-order-step-flag").textContent(), "1")
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$560.00" }).waitFor()

    await goTab("Add-ons", "addons")
    eq(await order.locator(".ck-option[data-disabled]").count(), 2, "both replica tiers are blocked")
    eq(await texts(order.locator(".ck-option-reason")), "Nothing to replicate yet: add storage first. | Nothing to replicate yet: add storage first. | Nothing to back up yet: add storage first.")
    eq(await order.locator("#ck-order-backups").isDisabled(), true)
    const gate = order.locator(".ck-order-gate")
    eq(await gate.locator(".alert-title").textContent(), "Finish the base first")
    eq(await texts(gate.locator(".ck-order-gate-list li > span")), "Machines need a boot volume: put storage on at least one tier. | Paste a public key, or switch to a password.")
    eq(await texts(gate.locator(".ck-order-fix")), "Fix in Storage | Fix in Infrastructure")
    eq(await order.locator(".ck-order-fieldset").evaluate((el) => el.disabled), true, "the add-ons wait")
    await gate.locator(".ck-order-fix", { hasText: "Storage" }).click()
    await panel("storage").waitFor()
    await setSlider("storage-t1", 500)
    await noneLeft('.ck-order-error[data-field="storage"]')
    eq(await order.locator(".ck-order-draw[data-over]").count(), 0)
  })

  await test("add-ons: protection and backups price themselves with deltas, and a blocked edge service says why", async () => {
    await reset()
    await fillKey()
    await goTab("Add-ons", "addons")
    eq(await order.locator(".ck-order-gate").count(), 0, "a valid base opens the add-ons")
    eq(await order.locator(".ck-order-fieldset").evaluate((el) => el.disabled), false)
    eq(await texts(order.locator(".ck-bcdr-item .item-title")), "Replica site | RPO and RTO | Backups")
    const tiers = order.locator('[data-section="protection"] .ck-option')
    eq(await texts(tiers.locator(".ck-option-name")), "NoneNo replica | Warm standbyRPO 15 min · RTO 1 hr · 25% of CPU and RAM | Hot standbyRPO 5 min · RTO 15 min · 100% of CPU and RAM")
    // 25% of ($40 + $480) + 975 GB at $0.05 + one licence; 100% for hot.
    eq(await texts(tiers.locator(".ck-option-delta")), "no change | +$193.75/mo | +$583.75/mo")
    eq(await order.locator(".ck-order-select").evaluate((el) => el.matches(":disabled, [aria-disabled='true'], [data-disabled]")), true, "the DR site waits for protection")
    await tiers.filter({ hasText: "Warm standby" }).click()
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$798.75" }).waitFor()
    eq(await texts(tiers.locator(".ck-option-delta")), "−$193.75/mo | no change | +$390.00/mo", "deltas re-price against the new choice")
    eq(await order.locator(".ck-order-select .select-value").textContent(), "SLC Cage 6 · Salt Lake City, UT")
    eq(await texts(order.locator('.ck-slider-row[data-field="drStoragePct"] .ck-slider-tick')), "100 | 125 | 150 | 175 | 200")
    const licences = order.locator(".ck-order-line", { hasText: "Replication licences" })
    eq(await licences.locator(".ck-order-line-price").textContent(), "$15.00/mo")
    eq(await licences.locator(".ck-order-line-meta").textContent(), "1 × $15.00")

    eq(await order.locator("#ck-order-backups").getAttribute("data-state"), "unchecked")
    eq(await order.locator('[data-section="backups"] .ck-switch-row .ck-delta').textContent(), "+$15.00/mo", "750 GB × $0.02")
    eq(await order.locator('[data-section="backups"] .ck-segments .toggle-group-item').first().isDisabled(), true, "retention waits for the switch")
    await order.locator("#ck-order-backups").click()
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$813.75" }).waitFor()
    await order.locator('[data-section="backups"] .ck-segments .toggle-group-item', { hasText: "30 days" }).click()
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$831.75" }).waitFor()
    const backupLine = order.locator(".ck-order-line", { hasText: "Backup storage" })
    eq(await backupLine.locator(".ck-order-line-price").textContent(), "$33.00/mo")
    eq(await backupLine.locator(".ck-order-line-meta").textContent(), "750 GB · 30 days")

    const addons = order.locator(".ck-check-row")
    eq(await addons.count(), 4)
    eq(await addons.first().locator(".checkbox").isDisabled(), true, "the firewall is included and cannot be dropped")
    eq(await addons.first().locator(".checkbox").getAttribute("data-state"), "checked")
    eq(await texts(addons.locator(".ck-delta")), "+$25.00/mo | +$40.00/mo | +$60.00/mo")
    await order.locator("#ck-addon-vpn").click()
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$856.75" }).waitFor()
    eq(await texts(addons.locator(".ck-delta")), "+$40.00/mo | +$60.00/mo", "a chosen add-on drops its delta")
    eq(await order.locator('[data-section="licences"] .ck-option-desc').textContent(), "No licensed software in this vDC; Linux images carry no licence fee.")

    // Without a public address the VPN and the shield are blocked, and the
    // one already chosen becomes an error the rail and the tab both carry.
    await goTab("Infrastructure", "infrastructure")
    await setSlider("ips", 0)
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$846.75" }).waitFor()
    await goTab("Add-ons", "addons")
    eq(await order.locator(".ck-check-row[data-disabled]").count(), 3, "firewall, VPN and DDoS")
    eq(await texts(order.locator(".ck-check-row .ck-option-reason")), "Needs at least one public IPv4 address (Infrastructure › Network). | Needs at least one public IPv4 address (Infrastructure › Network).")
    eq(await order.locator('.ck-order-error[data-field="addons"]').textContent(), "The VPN gateway and the DDoS shield need a public address.")
    eq(await tab("Add-ons").locator(".ck-order-step-flag").textContent(), "1")
    eq(await texts(order.locator(".ck-order-rail-issues .ck-order-issue")), "The VPN gateway and the DDoS shield need a public address.")
    await goTab("Infrastructure", "infrastructure")
    await setSlider("ips", 2)
    await order.locator(".ck-order-rail .ck-order-total-live", { hasText: "$856.75" }).waitFor()
    eq(await order.locator(".ck-order-step-flag").count(), 0)
  })

  await test("the table under the form: search, group by, columns, page size, row menus, machine settings, Add VM and Add vDC", async () => {
    await reset()
    const table = order.locator(".ck-order-table")
    const vdcRows = table.locator('tr[data-row="vdc"]')
    const vmRows = table.locator('tr[data-row="vm"]')
    eq(await vdcRows.count(), 1)
    eq(await vdcRows.locator(".data-table-group-label").textContent(), "vdc-01")
    eq(await style(vdcRows.locator(".data-table-group-label"), "textTransform"), "none", "a vDC name keeps its case")
    eq(await vdcRows.locator(".badge").textContent(), "Draft")
    eq(await texts(vdcRows.locator(".ck-vdc-facts > span")), "DFW Cage 6 | 20 GHz | 64 GB | 750 GB")
    eq(await vdcRows.locator(".ck-vdc-price-live").textContent(), "$605.00")
    eq(await vdcRows.locator(".ck-vdc-price-unit").textContent(), "/mo · $0.829/hr")
    eq(await vdcRows.locator(".data-table-group-toggle").getAttribute("aria-expanded"), "true", "groups open on arrival")
    eq(await vmRows.count(), 1)
    eq(await vmRows.locator('input[aria-label^="Name of"]').inputValue(), "vm-01")
    eq(await texts(vmRows.locator(".select-value")), "standard-2 | Ubuntu 24.04 LTS")
    eq(await vmRows.locator(".ck-vm-price .ck-hint").textContent(), "$34.00/mo", "2 vCPU × $2 + 4 GB × $7.50")
    const headers = () => table.locator("thead th").allTextContents()
    eq((await headers()).join(" | "), " | Machine | Site | Size | Image | Count | Pool draw | Actions", "vDC hides while grouped by it")

    // Search filters machines; the group row follows its machines.
    const search = order.locator(".ck-order-search-input")
    await search.fill("nothing-here")
    await table.locator(".ck-table-empty").waitFor()
    eq(await table.locator(".ck-table-empty").textContent(), "No machines match that filter.")
    await search.fill("vm-01")
    await vmRows.first().waitFor()
    eq(await vmRows.count(), 1)
    await search.fill("")

    // Group by site, then none, then vDC again; the grouped column hides.
    const menubar = order.locator(".ck-order-menubar")
    await menubar.locator(".menubar-trigger", { hasText: "Group by" }).click()
    await page.locator(".menubar-content .dropdown-menu-radio-item", { hasText: "Site" }).click()
    await table.locator(".ck-site-row").waitFor()
    await page.waitForFunction(() => [...document.querySelectorAll(".ck-order-table thead th")].some((th) => th.textContent === "vDC"))
    eq(await table.locator(".ck-site-row .data-table-group-label").textContent(), "DFW Cage 6")
    eq(await vdcRows.count(), 0)
    eq((await headers()).join(" | "), " | Machine | vDC | Size | Image | Count | Pool draw | Actions", "vDC shown, Site hidden")
    await menubar.locator(".menubar-trigger", { hasText: "Group by" }).click()
    await page.locator(".menubar-content .dropdown-menu-radio-item", { hasText: "None" }).click()
    await noneLeft(".ck-order-table .data-table-group-row")
    // The grouped column comes back in an effect, a render after the rows.
    await page.waitForFunction(() => [...document.querySelectorAll(".ck-order-table thead th")].some((th) => th.textContent === "Site"))
    eq((await headers()).join(" | "), " | Machine | vDC | Site | Size | Image | Count | Pool draw | Actions", "both shown ungrouped")
    await menubar.locator(".menubar-trigger", { hasText: "Group by" }).click()
    await page.locator(".menubar-content .dropdown-menu-radio-item", { hasText: "vDC" }).click()
    await vdcRows.first().waitFor()

    // Columns: hide Image, show it again.
    await menubar.locator(".menubar-trigger", { hasText: "Columns" }).click()
    const columns = page.locator(".menubar-content .dropdown-menu-checkbox-item")
    eq(await texts(columns), "vDC | Site | Size | Image | Count | Pool draw")
    await columns.filter({ hasText: "Image" }).click()
    await page.waitForFunction(() => ![...document.querySelectorAll(".ck-order-table thead th")].some((th) => th.textContent === "Image"))
    await page.keyboard.press("Escape")
    await menubar.locator(".menubar-trigger", { hasText: "Columns" }).click()
    await columns.filter({ hasText: "Image" }).click()
    await page.waitForFunction(() => [...document.querySelectorAll(".ck-order-table thead th")].some((th) => th.textContent === "Image"))
    await page.keyboard.press("Escape")

    // Density and page size are the kit's; the pager is the table's own (#39).
    eq(await order.locator('.ck-order-density .toggle-group-item[data-state="on"]').textContent(), "Compact")
    const compactPad = await style(vmRows.first().locator("td").first(), "paddingTop")
    await order.locator(".ck-order-density .toggle-group-item", { hasText: "Comfortable" }).click()
    await page.waitForFunction((p) => getComputedStyle(document.querySelector('.ck-order-table tr[data-row="vm"] td')).paddingTop !== p, compactPad)
    eq(parseFloat(await style(vmRows.first().locator("td").first(), "paddingTop")) > parseFloat(compactPad), true, "comfortable rows are taller")
    await order.locator(".ck-order-density .toggle-group-item", { hasText: "Compact" }).click()
    const pageSize = order.locator(".ck-order-pager .ck-page-size select")
    eq(await pageSize.inputValue(), "25")
    await pageSize.selectOption("10")
    eq(await pageSize.inputValue(), "10")
    eq(/^1–\d+ of \d+ rows$/.test(await order.locator(".ck-order-pager-range").textContent()), true, await order.locator(".ck-order-pager-range").textContent())
    eq(await order.locator('.ck-order-pages [aria-current="page"]').count(), 1, "page 1 is current")

    // Add VM, then a count that overdraws the pool becomes an error upstream.
    await order.locator(".ck-order-add-vm").click()
    await vmRows.nth(1).waitFor()
    eq(await vmRows.count(), 2)
    eq(await vdcRows.locator(".data-table-group-count").textContent(), "2")
    eq(await vmRows.nth(1).locator('input[aria-label^="Name of"]').inputValue(), "vm-02")
    const count = vmRows.nth(1).locator('input[aria-label^="Count of"]')
    await count.fill("12")
    await order.locator(".ck-order-rail-issues .ck-order-issue").waitFor()
    eq(await texts(order.locator(".ck-order-rail-issues .ck-order-issue")), "The machines draw 26 GHz; the CPU pool holds 20. Grow the pool or shrink a machine.")
    eq(await tab("Infrastructure").locator(".ck-order-step-flag").textContent(), "1")
    await count.fill("1")
    await noneLeft(".ck-order-rail-issues")

    // A row's chevron opens its settings under it.
    const expand = vmRows.first().locator(".ck-vm-expand")
    eq(await expand.getAttribute("aria-expanded"), "false")
    await expand.click()
    const detail = table.locator(".ck-vm-detail")
    await detail.waitFor()
    eq(await texts(detail.locator(".field-label")), "Public IP1 address | Nightly backup | Start after create")
    eq(await texts(detail.locator(".ck-segments .toggle-group-item")), "Tier 2 | Tier 3 | Tier 4")
    await detail.locator("#vm-1-ip").click()
    eq(await detail.locator("#vm-1-ip").getAttribute("data-state"), "checked")
    await expand.click()
    eq(await table.locator(".ck-vm-detail").count(), 0, "the chevron folds it away again")

    // The (…) menu and the right-click menu share their entries (#38).
    await order.locator('[aria-label="Actions for vm-02"]').click()
    const menu = page.locator('.dropdown-menu[data-state="open"]')
    eq(await texts(menu.locator(".dropdown-menu-item")), "Settings | Duplicate | Remove")
    await menu.locator(".dropdown-menu-item", { hasText: "Duplicate" }).click()
    await vmRows.nth(2).waitFor()
    eq(await vmRows.nth(2).locator('input[aria-label^="Name of"]').inputValue(), "vm-03")
    await vmRows.nth(2).locator(".ck-vm-price").click({ button: "right" })
    const context = page.locator('.ck-order-context[data-state="open"]')
    await context.waitFor()
    eq(await context.locator(".ck-context-label code").textContent(), "vm-03")
    eq(await texts(context.locator(".dropdown-menu-item")), "Settings | Duplicate | Remove")
    await context.locator(".dropdown-menu-item.ck-menu-danger").click()
    await page.waitForFunction(() => document.querySelectorAll('.ck-order-table tr[data-row="vm"]').length === 2)
    await vdcRows.first().locator(".ck-vdc-facts").click({ button: "right" })
    await context.waitFor()
    eq(await context.locator(".ck-context-label code").textContent(), "vdc-01")
    eq(await texts(context.locator(".dropdown-menu-item")), "Add to order | Add virtual machine | Duplicate")
    await context.locator(".dropdown-menu-item", { hasText: "Add virtual machine" }).click()
    await vmRows.nth(2).waitFor()
    await order.locator('[aria-label="Actions for vm-04"]').click()
    await menu.locator(".dropdown-menu-item.ck-menu-danger").click()
    await page.waitForFunction(() => document.querySelectorAll('.ck-order-table tr[data-row="vm"]').length === 2)

    // Add vDC refuses an invalid draft and lands on the problem; a valid one
    // joins the order and the form holds a new draft.
    const addVdc = order.locator(".ck-order-add-vdc")
    eq(await addVdc.textContent(), "Add vDC")
    await addVdc.click()
    await toastWith("Fix 1 problem before you add it to the order")
    await panel("infrastructure").waitFor()
    eq(await order.locator('.ck-order-error[data-field="access"]').count(), 1, "the refusal shows the error")
    eq(await vdcRows.count(), 1)
    await order.locator(".ck-order-key").fill(SSH_KEY)
    await order.locator(".ck-order-key").blur()
    await addVdc.click()
    await toastWith("vdc-01 added to the order")
    await vdcRows.nth(1).waitFor()
    eq(await texts(vdcRows.locator(".data-table-group-label")), "vdc-01 | vdc-02")
    eq(await texts(vdcRows.locator(".badge")), "Draft", "only the new draft wears a badge")
    eq(await vdcRows.nth(1).locator(".badge").count(), 1)
    eq(await texts(vdcRows.locator(".data-table-group-count")), "2 | 1", "vdc-01 kept both machines")
    eq(await order.locator(".ck-order-cart-count").textContent(), "2 vDCs1 in order")
    eq(await order.locator(".ck-order-cart-total").textContent(), "$1,210.00/mo")
    eq(await order.locator(".ck-order-rail-name code").textContent(), "vdc-02")

    // Edit adopts a committed vDC; while it is out, nothing deploys.
    await order.locator('[aria-label="Actions for vdc-01"]').click()
    eq(await texts(menu.locator(".dropdown-menu-item")), "Edit | Add virtual machine | Duplicate | Remove from order")
    await menu.locator(".dropdown-menu-item", { hasText: "Edit" }).click()
    await vdcRows.locator(".badge", { hasText: "Editing" }).waitFor()
    eq(await order.locator(".ck-order-rail-name code").textContent(), "vdc-01")
    eq(await addVdc.textContent(), "Add back to order")
    await goTab("Review", "review")
    eq(await order.locator(".ck-order-deploy-reason").textContent(), "vdc-01 is out of the order while you edit it; add it back first.")
    eq(await order.locator(".ck-order-deploy .ck-order-cta").isDisabled(), true)
    await addVdc.click()
    await toastWith("vdc-01 added to the order")
    await vdcRows.nth(2).waitFor()
    eq(await texts(vdcRows.locator(".data-table-group-label")), "vdc-01 | vdc-02 | vdc-03", "groups follow the machines, so the edited vDC keeps its place")
    await order.locator('[aria-label="Actions for vdc-02"]').click()
    await menu.locator(".dropdown-menu-item.ck-menu-danger").click()
    await page.waitForFunction(() => document.querySelectorAll('.ck-order-table tr[data-row="vdc"]').length === 2)
    await order.locator('[aria-label="Actions for vdc-01"]').click()
    await menu.locator(".dropdown-menu-item", { hasText: "Duplicate" }).click()
    await vdcRows.nth(2).waitFor()
    eq(await texts(vdcRows.locator(".data-table-group-count")), "2 | 1 | 2", "the copy took both machines")
    eq(await order.locator(".ck-order-cart-total").textContent(), "$1,815.00/mo")
  })

  await test("review: the receipt with tax and Change, the pinned hover card, JSON and CSV out, JSON back in, the link, the mail, the deploy", async () => {
    await reset()
    await fillKey()
    await goTab("Review", "review")
    eq(await order.locator(".ck-order-step-title").textContent(), "Review and deploy")
    eq(await order.locator(".ck-order-gate").count(), 0)
    const receipt = order.locator(".ck-receipt--page")
    eq(await texts(receipt.locator(".ck-receipt-group-name")), "Compute | Network | Storage")
    const line = (id) => receipt.locator(`[data-line="${id}"]`)
    eq(await line("cpu").locator(".ck-receipt-label").textContent(), "CPU pool20 GHz × $2.00")
    eq(await line("cpu").locator(".ck-receipt-hr").textContent(), "$0.055/hr")
    eq(await line("cpu").locator(".ck-receipt-amount").textContent(), "$40.00/mo")
    eq(await line("ipv6").locator(".ck-receipt-amount").textContent(), "included")
    eq(await line("storage-t1").locator(".ck-receipt-label").textContent(), "Tier 1 · HDD500 GB × $0.05")
    eq(await receipt.locator(".ck-receipt-line--sum .ck-receipt-amount").textContent(), "$605.00/mo")
    eq(await line("tax").locator(".ck-receipt-label").textContent(), "Estimated sales taxTX 8.25%")
    eq(await line("tax").locator(".ck-receipt-amount").textContent(), "$49.91/mo")
    eq(await receipt.locator(".ck-receipt-line--total .ck-receipt-amount").textContent(), "$654.91/mo")
    eq(await receipt.locator(".ck-receipt-line--total .ck-receipt-hr").textContent(), "$0.897/hr")
    eq(await receipt.locator(".ck-receipt-note").textContent(), "Monthly figures are a 730-hour estimate; usage bills hourly at month end.")
    eq(await style(line("cpu"), "display"), "grid")
    const cta = order.locator(".ck-order-deploy .ck-order-cta")
    eq(await cta.textContent(), "Deploy — $0.829/hr, up to $654.91/mo")
    eq(await cta.isDisabled(), false)
    eq(await order.locator(".ck-order-deploy-title").textContent(), "Deploys vdc-01 at DFW Cage 6")

    // Change jumps to the control that sets the line.
    await line("ram").locator(".ck-receipt-change").click()
    await panel("infrastructure").waitFor()
    eq(await order.locator('.ck-slider-row[data-field="ram"]').count(), 1)
    await goTab("Review", "review")

    // The rail's total hovers its receipt; a click pins it; Esc releases it.
    eq(await page.locator(".ck-order-receipt-card:popover-open").count(), 0)
    await glow.hover()
    const card = page.locator(".ck-order-receipt-card:popover-open")
    await card.waitFor()
    eq(await card.locator(".ck-receipt-line--total .ck-receipt-amount").textContent(), "$654.91/mo")
    eq(await card.locator(".ck-order-unpin").count(), 0)
    await glow.click()
    await order.locator(".ck-order-total-glow[data-pinned]").waitFor()
    eq(await glow.getAttribute("aria-pressed"), "true")
    await page.mouse.move(0, 0)
    await page.waitForTimeout(300)
    eq(await card.count(), 1, "pinned survives the pointer leaving")
    eq(await card.locator(".ck-order-unpin").textContent(), "Unpin")
    await page.keyboard.press("Escape")
    await noneLeft(".ck-order-receipt-card:popover-open")
    eq(await order.locator(".ck-order-total-glow[data-pinned]").count(), 0)

    // JSON out, JSON back in with a change, CSV out.
    const [json] = await Promise.all([page.waitForEvent("download"), order.locator(".ck-order-export-json").click()])
    eq(/^acme-order-\d{4}-\d{2}-\d{2}\.json$/.test(json.suggestedFilename()), true, json.suggestedFilename())
    const saved = JSON.parse(readFileSync(await json.path(), "utf8"))
    eq(saved.format, 1)
    eq(saved.order.draft.name, "vdc-01")
    eq(saved.order.vms.length, 1)
    saved.order.draft.name = "imported-vdc"
    saved.order.draft.cpu = 60
    saved.order.draft.junk = "<script>"
    const edited = join(tmpdir(), `vanillin-order-${Date.now()}.json`)
    writeFileSync(edited, JSON.stringify(saved))
    await order.locator(".ck-order-import-input").setInputFiles(edited)
    await toastWith("Order imported")
    eq(await order.locator(".ck-order-rail-name code").textContent(), "imported-vdc")
    eq(await total.textContent(), "$685.00", "60 GHz at $2 replaced 20")
    eq(await page.evaluate(() => JSON.parse(localStorage.getItem("vanillin.order.draft")).order.draft.junk), undefined, "unknown fields drop on the way in")
    const [csv] = await Promise.all([page.waitForEvent("download"), order.locator(".ck-order-export-csv").click()])
    eq(/\.csv$/.test(csv.suggestedFilename()), true)
    const rows = readFileSync(await csv.path(), "utf8").trim().split("\r\n")
    eq(rows[0], "kind,vdc,name,site,cpu_ghz,ram_gb,storage_gb,protection,image,size,count,monthly_usd,hourly_usd")
    eq(rows[1].startsWith("vdc,imported-vdc,imported-vdc,DFW Cage 6,60,64,750,None,Ubuntu 24.04 LTS,,1,685.00,"), true, rows[1])
    eq(rows.length, 3, "one vDC row and one machine row")

    // Copy link writes the order into the hash; mail carries the summary.
    eq(await page.evaluate(() => window.location.hash), "#order", "the hash is untouched until asked")
    await order.locator(".ck-order-copy-link").click()
    await order.locator(".ck-order-link").waitFor()
    const hash = await page.evaluate(() => window.location.hash)
    eq(hash.startsWith("#order?o="), true, hash.slice(0, 20))
    eq((await order.locator(".ck-order-link .copy-field-value").textContent()).includes("#order?o="), true)
    eq(await panel("review").count(), 1, "the route did not change under the hash")
    const mail = await order.locator(".ck-order-email").getAttribute("href")
    eq(mail.startsWith("mailto:?subject="), true)
    eq(decodeURIComponent(mail.slice("mailto:?subject=".length).split("&")[0]), "Acme Cloud order: 1 vDC, $685.00/mo")
    eq(decodeURIComponent(mail.split("&body=")[1]).includes("imported-vdc · DFW Cage 6 · 60 GHz · 64 GB · 750 GB · None — $685.00/mo ($0.938/hr)"), true)

    // The hash wins over the store; the store holds the order between visits.
    await clearStore()
    await arrive(hash)
    eq(await order.locator(".ck-order-rail-name code").textContent(), "imported-vdc", "the link restored the order")
    await arrive()
    eq(await order.locator(".ck-order-rail-name code").textContent(), "imported-vdc", "the store restored it")
    eq(await panel("location").count(), 1, "arrival is on Location")

    // Deploy: five stages, then the ways in and the payload.
    await fillKey()
    await goTab("Review", "review")
    await order.locator(".ck-order-deploy .ck-order-cta").click()
    const provision = order.locator(".ck-order-provision")
    await provision.waitFor()
    eq(await provision.getAttribute("data-state"), "running")
    eq(await texts(provision.locator(".ck-order-stages li")), "Reserving capacity | Carving the pools | Attaching the network edge | Writing images | Booting machines")
    eq(await provision.locator('.ck-order-stages li[data-state="running"]').count(), 1)
    eq(await order.locator(".ck-order-rail .ck-order-cta").isDisabled(), true, "the rail's Deploy is spent")
    await order.locator('.ck-order-provision[data-state="done"]').waitFor({ timeout: 8000 })
    eq(await provision.locator(".ck-order-provision-title").textContent(), "Deployed 1 vDC · $685.00/mo")
    eq(await provision.locator('.ck-order-stages li[data-state="done"]').count(), 5)
    const output = provision.locator('.ck-order-output[data-vdc="imported-vdc"]')
    eq(await output.count(), 1)
    eq(await texts(output.locator(".copy-field-label")), "SSH | Public IPv4 | Console")
    eq(await texts(output.locator(".copy-field-value")), "ssh ubuntu@203.0.113.10 | 203.0.113.10 | #console#vdc/imported-vdc")
    await provision.locator('[data-disclosure="api-payload"] .ck-disclosure-trigger').click()
    await provision.locator(".ck-order-payload-body").waitFor()
    const payload = JSON.parse(await provision.locator(".ck-order-payload-body").textContent())
    eq(payload.vdcs[0].name, "imported-vdc")
    eq(payload.vdcs[0].cpu_ghz, 60)
    eq(payload.vdcs[0].machines.length, 1)
    await provision.locator(".ck-order-footer .btn", { hasText: "Start another order" }).click()
    await panel("location").waitFor()
    eq(await order.locator(".ck-order-rail-name code").textContent(), "vdc-01")
    eq(await total.textContent(), "$605.00")
  })

  await test("at a phone's width the rail folds into a bar along the bottom that opens the receipt", async () => {
    await reset()
    await page.setViewportSize({ width: 700, height: 900 })
    await page.waitForFunction(() => getComputedStyle(document.querySelector(".ck-order-rail")).display === "none")
    const bar = order.locator(".ck-order-mobile")
    eq(await style(bar, "display"), "flex")
    eq(await style(bar, "position"), "sticky")
    eq((await style(order.locator(".ck-order-body"), "gridTemplateColumns")).split(" ").length, 1, "one column")
    eq(await bar.locator(".ck-order-mobile-live").textContent(), "$605.00")
    eq(await bar.locator(".ck-order-mobile-row .ck-order-continue").textContent(), "Continue to Infrastructure")
    eq(await bar.locator(".ck-receipt").isVisible(), false)
    await bar.locator(".ck-order-mobile-toggle").click()
    await bar.locator(".ck-receipt").waitFor()
    eq(await bar.locator(".ck-receipt-line--total .ck-receipt-amount").textContent(), "$654.91/mo")
    await goTab("Infrastructure", "infrastructure")
    eq((await style(order.locator(".ck-plans"), "gridTemplateColumns")).split(" ").length, 1, "plan cards stack")
    await page.setViewportSize({ width: 1280, height: 720 })
    await page.waitForFunction(() => getComputedStyle(document.querySelector(".ck-order-rail")).display !== "none")
  })

  // The suites share one page: leave the next one a clean store on #order.
  await clearStore()
  await arrive()
}
