import { lazy } from "react"

/**
 * All planned components. `page` is set once the component's demo page
 * exists; entries without one render greyed-out in the nav.
 */
export const registry = {
  primitives: { title: "Primitives (lib/)", page: lazy(() => import("./pages/primitives.jsx")) },
  accordion: { title: "Accordion", page: lazy(() => import("./pages/accordion.jsx")) },
  alert: { title: "Alert", page: lazy(() => import("./pages/alert.jsx")) },
  "alert-dialog": { title: "Alert Dialog", page: lazy(() => import("./pages/alert-dialog.jsx")) },
  "aspect-ratio": { title: "Aspect Ratio", page: lazy(() => import("./pages/aspect-ratio.jsx")) },
  attachment: { title: "Attachment", page: lazy(() => import("./pages/attachment.jsx")) },
  avatar: { title: "Avatar", page: lazy(() => import("./pages/avatar.jsx")) },
  badge: { title: "Badge", page: lazy(() => import("./pages/badge.jsx")) },
  breadcrumb: { title: "Breadcrumb", page: lazy(() => import("./pages/breadcrumb.jsx")) },
  bubble: { title: "Bubble", page: lazy(() => import("./pages/bubble.jsx")) },
  button: { title: "Button", page: lazy(() => import("./pages/button.jsx")) },
  "button-group": { title: "Button Group", page: lazy(() => import("./pages/button-group.jsx")) },
  calendar: { title: "Calendar" },
  card: { title: "Card", page: lazy(() => import("./pages/card.jsx")) },
  carousel: { title: "Carousel" },
  checkbox: { title: "Checkbox", page: lazy(() => import("./pages/checkbox.jsx")) },
  collapsible: { title: "Collapsible", page: lazy(() => import("./pages/collapsible.jsx")) },
  combobox: { title: "Combobox" },
  command: { title: "Command" },
  "context-menu": { title: "Context Menu" },
  "data-table": { title: "Data Table" },
  "date-picker": { title: "Date Picker" },
  dialog: { title: "Dialog", page: lazy(() => import("./pages/dialog.jsx")) },
  direction: { title: "Direction", page: lazy(() => import("./pages/direction.jsx")) },
  drawer: { title: "Drawer", page: lazy(() => import("./pages/drawer.jsx")) },
  "dropdown-menu": { title: "Dropdown Menu" },
  empty: { title: "Empty", page: lazy(() => import("./pages/empty.jsx")) },
  field: { title: "Field", page: lazy(() => import("./pages/field.jsx")) },
  "hover-card": { title: "Hover Card" },
  input: { title: "Input", page: lazy(() => import("./pages/input.jsx")) },
  "input-group": { title: "Input Group", page: lazy(() => import("./pages/input-group.jsx")) },
  "input-otp": { title: "Input OTP" },
  item: { title: "Item", page: lazy(() => import("./pages/item.jsx")) },
  kbd: { title: "Kbd", page: lazy(() => import("./pages/kbd.jsx")) },
  label: { title: "Label", page: lazy(() => import("./pages/label.jsx")) },
  marker: { title: "Marker", page: lazy(() => import("./pages/marker.jsx")) },
  menubar: { title: "Menubar" },
  message: { title: "Message", page: lazy(() => import("./pages/message.jsx")) },
  "message-scroller": { title: "Message Scroller", page: lazy(() => import("./pages/message-scroller.jsx")) },
  "native-select": { title: "Native Select", page: lazy(() => import("./pages/native-select.jsx")) },
  "navigation-menu": { title: "Navigation Menu" },
  pagination: { title: "Pagination", page: lazy(() => import("./pages/pagination.jsx")) },
  popover: { title: "Popover" },
  progress: { title: "Progress", page: lazy(() => import("./pages/progress.jsx")) },
  "radio-group": { title: "Radio Group", page: lazy(() => import("./pages/radio-group.jsx")) },
  resizable: { title: "Resizable" },
  "scroll-area": { title: "Scroll Area" },
  select: { title: "Select" },
  separator: { title: "Separator", page: lazy(() => import("./pages/separator.jsx")) },
  sheet: { title: "Sheet", page: lazy(() => import("./pages/sheet.jsx")) },
  sidebar: { title: "Sidebar" },
  skeleton: { title: "Skeleton", page: lazy(() => import("./pages/skeleton.jsx")) },
  slider: { title: "Slider", page: lazy(() => import("./pages/slider.jsx")) },
  spinner: { title: "Spinner", page: lazy(() => import("./pages/spinner.jsx")) },
  switch: { title: "Switch", page: lazy(() => import("./pages/switch.jsx")) },
  table: { title: "Table", page: lazy(() => import("./pages/table.jsx")) },
  tabs: { title: "Tabs", page: lazy(() => import("./pages/tabs.jsx")) },
  textarea: { title: "Textarea", page: lazy(() => import("./pages/textarea.jsx")) },
  toast: { title: "Toast (Sonner)" },
  toggle: { title: "Toggle", page: lazy(() => import("./pages/toggle.jsx")) },
  "toggle-group": { title: "Toggle Group", page: lazy(() => import("./pages/toggle-group.jsx")) },
  tooltip: { title: "Tooltip" },
  typography: { title: "Typography", page: lazy(() => import("./pages/typography.jsx")) },
}
