import { lazy } from "react"

/**
 * Docs pages — the shell around the component registry. Installation and
 * theming are stubs until the config generator and CLI land (tasks 37/38).
 */
export const docs = {
  introduction: { title: "Introduction", page: lazy(() => import("./pages/docs/introduction.jsx")) },
  installation: { title: "Installation", page: lazy(() => import("./pages/docs/installation.jsx")) },
  theming: { title: "Theming", page: lazy(() => import("./pages/docs/theming.jsx")) },
  schema: { title: "Schema", page: lazy(() => import("./pages/docs/schema.jsx")) },
}

/**
 * All planned components. `page` is set once the component's demo page
 * exists; entries without one render greyed-out in the nav.
 */
export const registry = {
  primitives: { title: "Primitives (lib/)", page: lazy(() => import("./pages/primitives.jsx")) },
  accordion: { title: "Accordion", page: lazy(() => import("./pages/accordion.jsx")) },
  alert: { title: "Alert", page: lazy(() => import("./pages/alert.jsx")) },
  "alert-dialog": { title: "Alert Dialog", page: lazy(() => import("./pages/alert-dialog.jsx")) },
  "aspect-ratio": { title: "Aspect Ratio", page: lazy(() => import("./pages/aspect-ratio.jsx")) },
  attachment: { title: "Attachment", page: lazy(() => import("./pages/attachment.jsx")) },
  avatar: { title: "Avatar", page: lazy(() => import("./pages/avatar.jsx")) },
  badge: { title: "Badge", page: lazy(() => import("./pages/badge.jsx")) },
  breadcrumb: { title: "Breadcrumb", page: lazy(() => import("./pages/breadcrumb.jsx")) },
  bubble: { title: "Bubble", page: lazy(() => import("./pages/bubble.jsx")) },
  button: { title: "Button", page: lazy(() => import("./pages/button.jsx")) },
  "button-group": { title: "Button Group", page: lazy(() => import("./pages/button-group.jsx")) },
  calendar: { title: "Calendar", page: lazy(() => import("./pages/calendar.jsx")) },
  card: { title: "Card", page: lazy(() => import("./pages/card.jsx")) },
  carousel: { title: "Carousel", page: lazy(() => import("./pages/carousel.jsx")) },
  checkbox: { title: "Checkbox", page: lazy(() => import("./pages/checkbox.jsx")) },
  collapsible: { title: "Collapsible", page: lazy(() => import("./pages/collapsible.jsx")) },
  combobox: { title: "Combobox", page: lazy(() => import("./pages/combobox.jsx")) },
  command: { title: "Command", page: lazy(() => import("./pages/command.jsx")) },
  "context-menu": { title: "Context Menu", page: lazy(() => import("./pages/context-menu.jsx")) },
  "data-table": { title: "Data Table", page: lazy(() => import("./pages/data-table.jsx")) },
  density: { title: "Density", page: lazy(() => import("./pages/density.jsx")) },
  "date-input": { title: "Date Input", page: lazy(() => import("./pages/date-input.jsx")) },
  "date-picker": { title: "Date Picker", page: lazy(() => import("./pages/date-picker.jsx")) },
  dialog: { title: "Dialog", page: lazy(() => import("./pages/dialog.jsx")) },
  direction: { title: "Direction", page: lazy(() => import("./pages/direction.jsx")) },
  drawer: { title: "Drawer", page: lazy(() => import("./pages/drawer.jsx")) },
  "dropdown-menu": { title: "Dropdown Menu", page: lazy(() => import("./pages/dropdown-menu.jsx")) },
  empty: { title: "Empty", page: lazy(() => import("./pages/empty.jsx")) },
  field: { title: "Field", page: lazy(() => import("./pages/field.jsx")) },
  form: { title: "Form", page: lazy(() => import("./pages/form.jsx")) },
  format: { title: "Format", page: lazy(() => import("./pages/format.jsx")) },
  "hover-card": { title: "Hover Card", page: lazy(() => import("./pages/hover-card.jsx")) },
  input: { title: "Input", page: lazy(() => import("./pages/input.jsx")) },
  "input-group": { title: "Input Group", page: lazy(() => import("./pages/input-group.jsx")) },
  "input-otp": { title: "Input OTP", page: lazy(() => import("./pages/input-otp.jsx")) },
  item: { title: "Item", page: lazy(() => import("./pages/item.jsx")) },
  kbd: { title: "Kbd", page: lazy(() => import("./pages/kbd.jsx")) },
  label: { title: "Label", page: lazy(() => import("./pages/label.jsx")) },
  marker: { title: "Marker", page: lazy(() => import("./pages/marker.jsx")) },
  menubar: { title: "Menubar", page: lazy(() => import("./pages/menubar.jsx")) },
  message: { title: "Message", page: lazy(() => import("./pages/message.jsx")) },
  "message-scroller": { title: "Message Scroller", page: lazy(() => import("./pages/message-scroller.jsx")) },
  "native-select": { title: "Native Select", page: lazy(() => import("./pages/native-select.jsx")) },
  "navigation-menu": { title: "Navigation Menu", page: lazy(() => import("./pages/navigation-menu.jsx")) },
  pagination: { title: "Pagination", page: lazy(() => import("./pages/pagination.jsx")) },
  popover: { title: "Popover", page: lazy(() => import("./pages/popover.jsx")) },
  progress: { title: "Progress", page: lazy(() => import("./pages/progress.jsx")) },
  "radio-group": { title: "Radio Group", page: lazy(() => import("./pages/radio-group.jsx")) },
  resizable: { title: "Resizable", page: lazy(() => import("./pages/resizable.jsx")) },
  "scroll-area": { title: "Scroll Area", page: lazy(() => import("./pages/scroll-area.jsx")) },
  select: { title: "Select", page: lazy(() => import("./pages/select.jsx")) },
  separator: { title: "Separator", page: lazy(() => import("./pages/separator.jsx")) },
  sheet: { title: "Sheet", page: lazy(() => import("./pages/sheet.jsx")) },
  sidebar: { title: "Sidebar", page: lazy(() => import("./pages/sidebar.jsx")) },
  skeleton: { title: "Skeleton", page: lazy(() => import("./pages/skeleton.jsx")) },
  slider: { title: "Slider", page: lazy(() => import("./pages/slider.jsx")) },
  spinner: { title: "Spinner", page: lazy(() => import("./pages/spinner.jsx")) },
  "status-dot": { title: "Status Dot", page: lazy(() => import("./pages/status-dot.jsx")) },
  switch: { title: "Switch", page: lazy(() => import("./pages/switch.jsx")) },
  table: { title: "Table", page: lazy(() => import("./pages/table.jsx")) },
  tabs: { title: "Tabs", page: lazy(() => import("./pages/tabs.jsx")) },
  textarea: { title: "Textarea", page: lazy(() => import("./pages/textarea.jsx")) },
  "time-picker": { title: "Time Picker", page: lazy(() => import("./pages/time-picker.jsx")) },
  toast: { title: "Toast (Sonner)", page: lazy(() => import("./pages/toast.jsx")) },
  toggle: { title: "Toggle", page: lazy(() => import("./pages/toggle.jsx")) },
  "toggle-group": { title: "Toggle Group", page: lazy(() => import("./pages/toggle-group.jsx")) },
  tooltip: { title: "Tooltip", page: lazy(() => import("./pages/tooltip.jsx")) },
  "use-form": { title: "useForm", page: lazy(() => import("./pages/use-form.jsx")) },
  typography: { title: "Typography", page: lazy(() => import("./pages/typography.jsx")) },
  "view-transitions": { title: "View Transitions", page: lazy(() => import("./pages/view-transitions.jsx")) },
}
